### ISSUE TITLE
‘Anonymize’ doesn't always work on filtered posts

### ISSUE THREAD

**Issue by emoloney** [ihavenoface/4chan-x#100]
If I filter by comment, I will still see the tripcode on the header of the filtered post.
![ss 2012-12-13 at 04 12 43 ](https://f.cloud.github.com/assets/2249431/11049/fc86cb34-453f-11e2-9071-2e24a18efab0.png)

**Comment by ihavenoface** [comment]
> doesn't always work

So sometimes it does, sometimes not?
~~Also please stop requesting the same issue on two githubs simultaneously.~~ Misread something there. But yeah, in general you should wait for one to either dismiss or fix the issue and go to the next one.
