### ISSUE TITLE
Master version + Firefox cross-thread #qp getting stuck

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#101]
I opened up this thread and hovered over the /q/ link and the quote preview gets stuck until I hover over a non-cross thread link. Image hover does not work while it is stuck.

http://boards.4chan.org/g/res/29833155

**Comment by ihavenoface** [comment]
Thanks. It's something with the IDColor as far as I can see here.

**Comment by ihavenoface** [comment]
76d3be47e3937a47f69b4edaa742f6df37f53f1e will fix the getting stuck but will essentially nuke coloring for hovered cross-board posts (which is broken). I'll redo IDColor tomorrow as it was quite bad anyway.
