### ISSUE TITLE
In the event of 4chan Pass errors, quick reply stays in endless loop

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#102]
See: http://i.imgur.com/HBDfc.png

Nothing in console aside from it keep trying to post.

**Comment by ihavenoface** [comment]
I have no way to test for that.

**Comment by seaweedchan** [comment]
Mayhem has a 4chan pass, make an issue there or something and see if he'll fix it.

**Comment by ihavenoface** [comment]
![bc2](https://f.cloud.github.com/assets/1175752/11524/f2f7c1e8-4555-11e2-92a3-16ed6d6e8da0.png)

**Comment by ihavenoface** [comment]
Has been fixed, supposedly.
