### ISSUE TITLE
Nightly Insta-Crash on Post

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#103]
It's a bug on Nightly's behalf: www.bugzil.la/821733
I'm just posting this for reference since I'd assume you'd at least get a few posts about it.

**Comment by ihavenoface** [comment]
Thanks for the reference.

**Comment by Guillimet** [comment]
For what it's worth, I can also confirm this is happening.

**Comment by vampiricwulf** [comment]
It's fixed.
