### ISSUE TITLE
Part of Announcement Not Displaying

### ISSUE THREAD

**Issue by Guillimet** [ihavenoface/4chan-x#104]
With the current announcement, "You can now purchase 4chan Passes using Bitcoin. Click here to learn more and purchase." appears for a short amount of time, and then vanishes.

This doesn't happen with the rest of the announcement, for whatever reason.

**Comment by ihavenoface** [comment]
Do you have any other userscripts besides 4chan x / userstyles / adblocker / whatever could block or hide text nodes running? ~~I'm pretty sure 4chan x isn't touching this area at all.~~
Looked again - one second.

**Comment by Guillimet** [comment]
Nope, I disabled everything but Greasemonkey, and every script but 4chan X, but it's still happening.

What's more, it doesn't seem to be happening in Mayhem's 4chan X.

Obviously, it isn't the end of the world, but it seems odd.

**Comment by ihavenoface** [comment]
Try 230e1b41d7b0f7eb3335d26cc443391af9bff337?

**Comment by Guillimet** [comment]
Alright, that seems to work.
