### ISSUE TITLE
Error: TypeError: $.id(...) is null

### ISSUE THREAD

**Issue by Tyronic** [ihavenoface/4chan-x#106]
Error: TypeError: $.id(...) is null
Source File: https://static.4chan.org/js/extension-compiled.549.js
Line: 14

Seems to be fixed

**Comment by vampiricwulf** [comment]
Any symptoms?

**Comment by Tyronic** [comment]
Nothing other than a constant pop up.

`URL: https://boards.4chan.org/v/res/167186168
Time.node@file:///C:/Users/Jacob/AppData/Roaming/Mozilla/Firefox/Profiles/jg1zm7au.default/gm_scripts/4chan_x/4chan_x.user.js:3945
Main.node@file:///C:/Users/Jacob/AppData/Roaming/Mozilla/Firefox/Profiles/jg1zm7au.default/gm_scripts/4chan_x/4chan_x.user.js:6606
Main.featuresReady@file:///C:/Users/Jacob/AppData/Roaming/Mozilla/Firefox/Profiles/jg1zm7au.default/gm_scripts/4chan_x/4chan_x.user.js:6528
.ready/cb@file:///C:/Users/Jacob/AppData/Roaming/Mozilla/Firefox/Profiles/jg1zm7au.default/gm_scripts/4chan_x/4chan_x.user.js:351`

**Comment by ihavenoface** [comment]
If anything I wouldn't even know what's wrong with `Time` and it's hard to test for bugs since they obviously depend on the users timezone.
