### ISSUE TITLE
‘Quote Inline’ and ‘Quote Preview’ break Layout when used with ‘Replace <imgtype>’ and Custom CSS

### ISSUE THREAD

**Issue by emoloney** [ihavenoface/4chan-x#107]
When I use this custom CSS

div.file, a.fileThumb img {
  width: 200% !important;
  height: 200% !important;
  float: left; 
}

with the ‘Replace <imgtype>’ options ‘Quote Inline’ and ‘Quote Preview’ both cause thumbnails to be expanded to 200% of their native image size, whereas before, they just were 200% of the default thumbnail size.

Yes noface
don't use the CSS
don't use replace images
don't use Quote Inline or Quote Preview

I have many options. I just thought you might want to know about the bug. 

“Your css has a bug, not 4chan x.” Oh yeah? What makes you sure that it's in those four lines, and not in the four thousand in 4chan x? The bug only shows up when using ‘Quote Inline’ and ‘Quote Preview’. That indicates to me that the bug is in ‘Quote Inline’ and ‘Quote Preview’.

**Comment by ihavenoface** [comment]
Don't use that css then?

Your css has a bug, not 4chan x.

**Comment by emoloney** [comment]
“Your css has a bug, not 4chan x.” Oh yeah? What makes you sure that it's in those four lines, and not in the four thousand in 4chan x? The bug only shows up when using ‘Quote Inline’ and ‘Quote Preview’. That indicates to me that the bug is in ‘Quote Inline’ and ‘Quote Preview’.

**Comment by ihavenoface** [comment]
> What makes you sure that it's in those four lines, and not in the four thousand in 4chan x? 

Because whoever wrote this obviously doesn't know how css works.

**Comment by emoloney** [comment]
What makes it obvious?

By the way, the issue also occurs when threads have an image post added by the autoupdate.

**Comment by ihavenoface** [comment]
> What makes it obvious?

The css.

**Comment by emoloney** [comment]
The guy who wrote it has many le upboats on stackoverflow. I daresay your deductions are flawed.

**Comment by ihavenoface** [comment]
Then why does my example work?

**Comment by emoloney** [comment]
Oh, sorry; I wasn't very clear in my “steps to reproduce the glitch”.

You have to click on a quote link to an image post. For example, if someone quotes the OP, if you click on that, the inline expansion will show an image twice the size of the native res instead of a 500px one.

**Comment by ihavenoface** [comment]
I already told you that your css is at fault. Blocking you now.
