### ISSUE TITLE
Option to adjust the thread watcher's size

### ISSUE THREAD

**Issue by emoloney** [ihavenoface/4chan-x#108]
It would be nice to have an option to show more or fewer threads on the watcher before it starts hiding.

**Comment by ihavenoface** [comment]
Isn't the height of the Thread Watcher is already dependant on the amount of threads watched?
Or do you mean something like drag-to-resize?

**Comment by emoloney** [comment]
I mean, at the moment it will show n threads at once, growing as new threads are added. However, once n reaches a certain limit, x, the thread watcher will only show the first x threads being watched, requiring a mouseover to view all n that it is, in fact, watching. I would like to be able to adjust x.

**Comment by ihavenoface** [comment]
Ah alright.
