### ISSUE TITLE
"quote.match(...) is null"

### ISSUE THREAD

**Issue by Guillimet** [ihavenoface/4chan-x#109]
The following text popped up and told me to report this, after I clicked "/g/" at the top of the page. I'm running Oneechan and Linkify+.

URL: https://boards.4chan.org/g/
Quotify.node@file:///C:/Users/[Username]/AppData/Roaming/Mozilla/Firefox/Profiles/[profilename].default/gm_scripts/4chan_x/4chan_x.user.js:5209
Main.node@file:///C:/Users/[Username]/AppData/Roaming/Mozilla/Firefox/Profiles/5lwddpzb.default/gm_scripts/4chan_x/4chan_x.user.js:6606
Main.featuresReady@file:///C:/Users/[Username]t/AppData/Roaming/Mozilla/Firefox/Profiles/5lwddpzb.default/gm_scripts/4chan_x/4chan_x.user.js:6528
.ready/cb@file:///C:/Users/A[Username]/AppData/Roaming/Mozilla/Firefox/Profiles/5lwddpzb.default/gm_scripts/4chan_x/4chan_x.user.js:351

**Comment by ihavenoface** [comment]
Should have been fixed with b7d4aef48a6ad3758347b5473c028265b7886a13 which is still in the master.

On a different note - Linkification is built-in by now so you might want to exlude Linkify+ on 4chan.
