### ISSUE TITLE
Regex includes in Chrome not working

### ISSUE THREAD

**Issue by spaghetti2514** [ihavenoface/4chan-x#110]
Script does not seem to be loading in Chrome since the addition of the regex includes.

**Comment by seaweedchan** [comment]
It works fine with Tampermonkey, but the install page doesn't play well with Tampermonkey since there's no direct link to the userscript for some retarded reason.

Install Tampermonkey, then install the master version of 4chan X, and everything should work fine.

**Comment by spaghetti2514** [comment]
What exactly does the regex include add that justifies needing another extension just to use this one?

**Comment by seaweedchan** [comment]
Its cleaner, probably the only reason.

Using Tampermonkey is a good idea anyway. You use Greasemonkey in Firefox to get more control and features in userscripts, same goes for Tampermonkey.

**Comment by spaghetti2514** [comment]
I mean, I would have liked to not lose everything in my thread watcher, filter, and settings as a result of changing the script loader.
But hey, at least the script is only 7218 lines now instead of 7223.

**Comment by ihavenoface** [comment]
People are still running their scripts without tampermonkey?

**Comment by seaweedchan** [comment]
>But hey, at least the script is only 7218 lines now instead of 7223.
Oh you

**Comment by ihavenoface** [comment]
> since there's no direct link to the userscript for some retarded reason.

Noticed that too. Lemme change that.
