### ISSUE TITLE
Limit image loading/expansion

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#111]
Hi.
I have a shitty internet and sometimes when trying to expand all the images in a thread, it's very slow and some of them end up truncated or corrupted and I can't see them properly unless I reload the image overriding cache. I was wondering if something could be implemented so one can specify the max amount of images that can be loaded or expanded at the same time to reduce timeout errors.
Thanks :))

**Comment by ihavenoface** [comment]
Is this still a thing?
Feel free to comment if it is.
