### ISSUE TITLE
Bing image sauce

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#112]
Here's a "Other sizes" page for one image on Bing:
http://www.bing.com/images/search/?q=seattle&cbir=ms&mid=DD42AAEFCE5705391BF8AE4ABAE78F7EA99D9A39

And here's a "Similar images" result for the same image:
http://www.bing.com/images/search?q=seattle&rxc=15&simid=5065536767459963&sid=DD42AAEFCE5705391BF8AE4ABAE78F7EA99D9A39

Is there a way to add sauce entries for these?

**Comment by ihavenoface** [comment]
Not if I don't know where to put the url of the image.
