### ISSUE TITLE
Announcement toggle

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#113]
See default 4chan extension

**Comment by ihavenoface** [comment]
I've thought about this several times but then I always lacked a pretty icon.

Thanks for suggestion.

**Comment by seaweedchan** [comment]
You could always go with [Hide].

A better idea would be to copy the announcement to a new variable, check on every reload if the announcement and the new variable are the same, and have a [Dismiss] link that hides the announcement until it is different.

**Comment by kweeb** [comment]
> A better idea would be to copy the announcement to a new variable, check on every reload if the announcement and the new variable are the same, and have a [Dismiss] link that hides the announcement until it is different.

I've been hoping for a long time that someone would make something like this.

**Comment by ihavenoface** [comment]
![derp](https://f.cloud.github.com/assets/1175752/26949/e23f0286-4b62-11e2-927a-d7e239093521.png)

How does this look?

**Comment by kweeb** [comment]
Very good.

**Comment by ihavenoface** [comment]
Here you go - f7a4dc59fade6165c0ba407f4b110dd880b351b1

Still a mess but should work™.
Feel free to test.

**Comment by seaweedchan** [comment]
Not sure what "Dismiss" and "Detain" are supposed to do. They don't seem to do anything.

Could I get an extra class for #hideBtn when its hidden? class=hidden

**Comment by ihavenoface** [comment]
When you see 'Detain' we will store the current content of the message and compare it again on each refresh. Should it differ the message won't be hidden anymore.

Sure.

**Comment by seaweedchan** [comment]
As in if I do Dismiss and then Hide it will unhide when the announcement is new? "Detain" isn't very explanatory, and why not make Dismiss auto-hide as well?

**Comment by ihavenoface** [comment]
Yes.
Could add some tooltip to it.
Because it would require me to go two ways instead of one to change a single setting. This is more straightforward in my opinion.

**Comment by seaweedchan** [comment]
Alright well what about the hidden class? Things shift around and require repositioning depending on if the announcement is there or not, would be nice. Not to mention that I'd like to manually get rid of the useless Detain button when its hidden.

**Comment by ihavenoface** [comment]
@seaweedchan, here e25439884b6c07f22acab036a61345887aa6442d is the class you wanted.
Does this thing work by the way?

**Comment by seaweedchan** [comment]
I mostly still hate this entire implementation.

Most people don't know how it works in the first place. They don't know what detain means. They don't understand why hitting Dismiss on its own does not actually dismiss anything.

Its not even a part of #globalMessage meaning if you move the announcement around it just gets placed weirdly.

I just don't like it, and I don't think I'm alone on that.
