### ISSUE TITLE
Expose various textContents to the rice tab

### ISSUE THREAD

**Issue by kweeb** [ihavenoface/4chan-x#114]
Like the menubutton, navigation buttons, embedder, OP/dead on quotelinks, captcha input placeholder (can't seem to change it on nightly after [bug 737786](https://bugzilla.mozilla.org/show_bug.cgi?id=737786)).. and I think that's all.

Of course it's something css can do but I think it would be cool to have them customizable within the script options.

**Comment by ihavenoface** [comment]
Thanks for your suggestions.
Someone expressed something similar in #76 so I guess I'll look into that sooner or later.

**Comment by seaweedchan** [comment]
Something worth noting for the menu button is that you'd have to remove the border styling if the textcontent for it is changed since it doesn't actually use text for the arrow.
