### ISSUE TITLE
#qp styling stuff

### ISSUE THREAD

**Issue by kweeb** [ihavenoface/4chan-x#115]
I started ricing 4chan again and noticed that this is _still_ a thing?
Giving .reply a border and a background gives #qp them twice.
Of course I can fix that in my css but I don't think it should be happening and since others will now also get into styling due to Oneechan dying, I think it would be good to finally fix that.
It's kind of an issue mostly because the #qp is hard to inspect due to it being removed from the DOM on mouseout.

Another thing to note about the #qp is that OPs in it have the menubutton and reply-link which shouldn't be.

**Comment by ihavenoface** [comment]
I could give #qp a different class and restyle it but I don't know yet if this would be cool and at what point it will break.

> due to it being removed from the DOM on mouseout.

For the sake of writing the style you could simply remove the event.

> Another thing to note about the #qp is that OPs in it have the menubutton and reply-link which shouldn't be.

The OP doesn't have those by default?

**Comment by kweeb** [comment]
> I could give #qp a different class and restyle it but I don't know yet if this would be cool and at what point it will break.

Whatever would be best in the long run. Currently there aren't many styles or scripts you'd be breaking whatever you choose to do.

> For the sake of writing the style you could simply remove the event.

I have done this in the past and will do it again.

> The OP doesn't have those by default?

Is that a question?
What I'm saying is - when hovering a quotelink that points to the OP, the #qp has a menubutton if the menu is enabled, and doing that on an index page shows the [Reply] link.
Both the menu and the link are inaccessible from the #qp so there's no reason to have them there.
They are also present when the OP gets inlined to a reply but that's ok I suppose.

Actually, the menubutton also appears in replies, as long as they are already on the page (not inside an unexpanded thread or cross-thread).

**Comment by seaweedchan** [comment]
> It's kind of an issue mostly because the #qp is hard to inspect due to it being removed from the DOM on mouseout.

Just give another div the qp ID in your browser's inspector, or use Opera which doesn't allow elements to close during inspection (but will allow you to open #qp still)

**Comment by kweeb** [comment]
> Just give another div the qp ID in your browser's inspector

That would achieve absolutely nothing of use.

> or use Opera

Nah.

**Comment by seaweedchan** [comment]
> That would achieve absolutely nothing of use.

You're trying to see the styling for it, no? That's one way to do it.

**Comment by kweeb** [comment]
Ah, not a bad idea but it doesn't really give me any representation of #qp because it has different descendants.
It's fine though, I already have my #qp looking ok but I'm just leaving out there the idea that the #qp should be just one DIV instead of a DIV in a DIV, and it's extra weird because they're both .reply. I'm sure the original nested design was because of tables.

This issue could also be merged into #118.
