### ISSUE TITLE
Post expansion minor cosmetic

### ISSUE THREAD

**Issue by kweeb** [ihavenoface/4chan-x#116]
> Comment too long. Click **here** to view the full text.

Becomes

> Comment too long. Click **Loading No.xxxxxxx...** to view the full text.

Seems silly to me. Maybe I'm just really autistic.
Would just look better if it only had the Loading No. xxxxxxxx... part.

Post expansion also doesn't work on Nightly (post.el is undefined) but Nightly is Nightly and it's no big deal.

**Comment by ihavenoface** [comment]
I would get even more autistic about the text I just clicked jumping out of my reach.
Personally I prefer the current, static version.

**Comment by kweeb** [comment]
Fair enough~
