### ISSUE TITLE
Duplicate file entry and deletion

### ISSUE THREAD

**Issue by kweeb** [ihavenoface/4chan-x#117]
When trying to upload an image that has already been uploaded, you get a message and link to the post containing the image, which is great, but:

Would it be possible to have another link there to attempt deletion of the image right there from the QR?

Would it be possible to tamper with the currently selected image to change its checksum within 4chan X before reuploading?

Also, trying to delete images from the menu often fails, and the menu stll says 'Deleted'.

**Comment by ihavenoface** [comment]
@kweeb 
Not interested anymore?

**Comment by kweeb** [comment]
I'm not sure, to be honest.
I don't use your fork anymore (I don't really go on 4chan these days anyway, just installed mayhem v3 once when it was still in testing), and I just thought I'd close these issues I had here because with v3 I have no idea if these issues are even valid anymore.
If you think they are still valid, feel free to reopen them, but I don't really care about them personally anymore.

**Comment by ihavenoface** [comment]
Fair enough. Have a nice day then.

**Comment by kweeb** [comment]
Nice day to you too~
