### ISSUE TITLE
Menu entry for hiding replies/threads

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#119]
I feel that the hide buttons are unnecessary with the menu, and would like to be able to get rid of them entirely without losing that functionality.

AppChan X, OneeChan, and Style Script have all added this entry, but that leaves anyone on plain userstyles (or vanilla 4chan) out entirely.

**Comment by ihavenoface** [comment]
Wise decision.

**Comment by zixaphir** [comment]
https://github.com/zixaphir/appchan-x/blob/4chanX/src/filtering/replyhiding.coffee
https://github.com/zixaphir/appchan-x/blob/4chanX/src/menu/replyhidelink.coffee

https://github.com/zixaphir/appchan-x/blob/4chanX/src/filtering/threadhiding.coffee
https://github.com/zixaphir/appchan-x/blob/4chanX/src/menu/threadhidelink.coffee
