### ISSUE TITLE
Hiding global announcement

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#121]
Can we please get an option to hide the 4chan Gold Account ads? I don't feel that AdBlock is necessary.

**Comment by ihavenoface** [comment]
#113

**Comment by ididntknowicoulddothatXD** [comment]
Whoops, missed that.

Thanks in advance.

Testing samthing.
http://imgur.com/a48p8.jpg
http://imgur.com/J3UsE.gif
