### ISSUE TITLE
Thread Watcher Update 2

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#122]
I know I already asked for this but
![](https://images.4chan.org/q/src/1356555869871.png)
is making me jealous. Would it be possible to add an update feature to the TW?

``Race'' garbage aside, I think this really would be a good improvement.

**Comment by ihavenoface** [comment]
We have the same thing here #64 and I understand that you want this but I won't write it faster only because you ask me more often about it.
