### ISSUE TITLE
Export / Import of userprefs.

### ISSUE THREAD

**Issue by ihavenoface** [ihavenoface/4chan-x#123]

**Comment by milkytiptoe** [comment]
As in to/from a file?

There's no way to trigger a save as dialog in JS, though?

**Comment by ihavenoface** [comment]
I was under the impression that the download attribute does support data blobs?
Could also implement it with "copy text -> paste in file"(TM).

**Comment by milkytiptoe** [comment]
The download attribute does not trigger a save as dialog. In Chrome at least, it autosaves to the default download directory.

If that's 'good enough' then alright.

**Comment by ihavenoface** [comment]
> The download attribute does not trigger a save as dialog.

Oh, you're right of course.
