### ISSUE TITLE
Linkifier slightly broken by an html change

### ISSUE THREAD

**Issue by kweeb** [ihavenoface/4chan-x#124]
A developer popped in on /g/ announcing he made changes to wordwrapping.
Apparently what he did included inserting [WBRs](https://developer.mozilla.org/en-US/docs/HTML/Element/wbr) into long strings of characters without spaces.
This ends any hyperlinked text prematurely and shift-clicking doesn't fix them either.

**Comment by ihavenoface** [comment]
I'll fix this next year. Thanks for reporting.

**Comment by seaweedchan** [comment]
I don't see why you can't just fix this now. Just remove all instances of <wbr>

**Comment by ihavenoface** [comment]
> Just remove all instances of  <wbr>

You are sure this is safe to do? Then again some stuff isn't done yet so I won't push it to stable just now anyway.

**Comment by seaweedchan** [comment]
Its safe to do if you don't care about the three Opera Mobile users using 4chan X with the mobile site, who I think would argue that they'd rather have non-broken links than care about word breaks.

**Comment by seaweedchan** [comment]
Poke.

13 days is a long time to go leaving a whole feature of 4chan X broken.

**Comment by skillface** [comment]
Still waiting on a fix for this.

**Comment by Poilaucul** [comment]
Fix please.

**Comment by ihavenoface** [comment]
246aa7daef28eb315c3a272408369c58249e8639 should do the trick for manually concatenating urls.

**Comment by seaweedchan** [comment]
Now even that is broken, and concatenating them every time would hardly be a solution anyway.

http://i.imgur.com/G9t3I.png

**Comment by ihavenoface** [comment]
What is broken exactly?
The issue isn't closed yet, right?

**Comment by seaweedchan** [comment]
Just look at the image. If you try to concatenate the two, nothing will happen at first, and then the TEXT turns into broken link + ENTIRE text good link, with the anchor simply being to the broken link.

**Comment by randyzie** [comment]
Curious if this issue has had any more progress.

**Comment by ihavenoface** [comment]
@randyzie 
http://rbt.asia/g/thread/30855209

**Comment by randyzie** [comment]
Ah, alright thanks.

**Comment by seaweedchan** [comment]
Its been 24 days for one little element...

**Comment by ihavenoface** [comment]
Then you will be glad to hear that it's making progress.
![142](https://f.cloud.github.com/assets/1175752/87211/aecb7d48-64b8-11e2-8339-50ac901da363.png)

Seriously though, it won't get ready sooner the more often you ask for it. I'm not doing this out of ignorance but because I want to write it right and considering the amount of time I currently have to write on scripts is kind of short this here will eventually delayed even further.

**Comment by ihavenoface** [comment]
Here's a compromise for now c46627e69d5d32aecee4f496da3de2b6ed8de619.
