### ISSUE TITLE
Using drop-down filter menu auto scrolls up to mid page

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#126]
Often, clicking outside the 4chan X menu box to close it after adding a filter using the drop-down menu will auto scroll the tab up to some point near the mid of the thread, as if I clicked an anchor link pointing to there. This happens more often when filtering by md5, it's annoying when I try to add several images in the bottom part of a thread to get taken to the middle of the page every time. The auto scrolling always happens upwards and is more common when filtering stuff near the end of the thread. I don't know what triggers this behavior.

**Comment by ihavenoface** [comment]
I take you are using Nigthly?

**Comment by usernamestring** [comment]
No, I'm using latest stable (17.0.1). I created a new profile with only Scriptish and 4chan X installed to see if other extensions cause this behavior but the problem still happens.

**Comment by ihavenoface** [comment]
I'll have a look at it ~~tomorrow~~.

Please don't use Scriptish, use Greasemonkey instead if possible.

**Comment by ihavenoface** [comment]
Probably fixed with v3. Feel free to comment here if not.
