### ISSUE TITLE
<wbr> fucking with embeds

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#127]
moot decided to be a faggot casual again and added more moralfag support for THE POOR POOR MOBILE BROWSERS ;_____________________________;.

Which results into links stopping earlier. Which THEN results into fucking YT links up. http://puu.sh/1K2y2
That's how it looks in the archive: http://archive.heinessen.com/mlp/thread/7133694#p7133907

www.youtube.com/watch?feature=player_detailpage&v=lksvMF<wbr>cQcaw

Is it possible to change something.

**Comment by ihavenoface** [comment]
#124
I will fix this with the next changes of Linkifier and Embedder which are not yet quite complete.
