### ISSUE TITLE
"Connection Error with sys.4chan.org" on successful posts

### ISSUE THREAD

**Issue by Poilaucul** [ihavenoface/4chan-x#130]
Post is successful but I still get those errors.

**Comment by ihavenoface** [comment]
What version of 4chan x are you using?

**Comment by randyzie** [comment]
So far it seems to be working on the new 2.37.8, either it fixed it or it was on 4chans end.

**Comment by ihavenoface** [comment]
4chan x was looking for a specific condition on the `Post successful!` page. Now 4chan removed the element which gave the hiccup.
Also yeah, it's fixed in 4925d584a0e0488a3778fe5f60ac763be1c2d204 so I'll close this.

**Comment by Poilaucul** [comment]
I am using 2.37.8
