### ISSUE TITLE
Keep getting ``You are banned'' false positives

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#132]
And they usually redirect to https://boards.4chan.org/q/undefined or https://boards.4chan.org/w/undefined etc.

**Comment by doormeetface** [comment]
Getting the same error. Deleting cache seems to have helped.

**Comment by ihavenoface** [comment]
Deleting the cache might help though the undefined shouldn't be there.

**Comment by Norfag** [comment]
I had somewhat similar problem, but after deleting the catch I keep getting "Connection error with sys.4chan.org." and, "Error: You must wait 58 seconds before posting a duplicate reply." after it retries.
The post will succeed being posted, but the post fields wont reset themselves. (Comment, Image, etc).

**Comment by seaweedchan** [comment]
Norfag,  you need to update 4chan X. That was an issue with a change in the Post Successful page.

**Comment by Norfag** [comment]
welp, updated 1-2 days ago, and it went into 2.37.7, and now I see a 2.37.8 update dated 3 days.
Fixed it, thanks mate, and I love you for Oneechan.

edit: why did you end it ;_;

**Comment by seaweedchan** [comment]
Might have been an issue with tags.

And OneeChan was just Style Script with some minor differences. A lot of those differences have already been merged back into Style Script.

**Comment by ghost** [comment]
Same problem here. Deleting cache and updating 4chan X did nothing. Only thing different is it properly links me to the ban page which then redirects to the main page because I'm not banned.

**Comment by ihavenoface** [comment]
I probably won't port Ban Checker to v3.
