### ISSUE TITLE
Font Distortion.

### ISSUE THREAD

**Issue by ScrapBone** [ihavenoface/4chan-x#133]
For some reason the script causes the font to become jagged when in a thread but seems fine if your viewing the rest of the board. It also has a jagged font for the thread watcher.

This did not occur until after I switched to Firefox 18 but the issue only happens when the script is enabled

**Comment by ihavenoface** [comment]
> This did not occur until after I switched to Firefox 18 

This is probably the fix. There was a bug in Firefox where javascript events like hover, refresh or scrolling would act on text nodes like the way you described, completely random. I've noticed that as well.

Furthermore the script _can't_ be at fault as everything is just text.

**Comment by ScrapBone** [comment]
Thanks for the reply. What can be done about it? Should I uninstall java and/or reinstall? Or should I reinstall Firefox?

**Comment by ihavenoface** [comment]
Well you are using a newer version of Firefox? This should do the trick.

**Comment by seaweedchan** [comment]
> This is probably the fix.

He's saying he updated to the current stable and then started having the issue.

**Comment by ihavenoface** [comment]
> This did not occur until after I switched to Firefox 18
> after

Then again there's nothing I can do about his browser acting weird.

**Comment by seaweedchan** [comment]
UNTIL after. 

And true dat. Works fine here

**Comment by kweeb** [comment]
Could you post an image of the issue?
OS?
Do you have HW acceleration on?

**Comment by Tablecat** [comment]
http://bugzilla.mozilla.org/show_bug.cgi?id=812695

**Comment by ScrapBone** [comment]
Than you for the response and excuse my slow reply.
I'm still using XP cause I'm still broke and HW  acceleration is off. I also uninstalled and re installed the latest java to no avail.
The only thing that helps is zooming out or in at least one level

**Comment by ihavenoface** [comment]
> I also uninstalled and re installed the latest java to no avail.

Not necessary as this here JavaScript, not Java which are two different things.
I'll close this issue as it isn't related to this fork.
