### ISSUE TITLE
Start updating the changelog again 

### ISSUE THREAD

**Issue by Croakier** [ihavenoface/4chan-x#134]
It's pretty lame to get an update and not know what it did, I actually read the changelog every chance I get.

**Comment by ihavenoface** [comment]
I'll continue it in the next release, see #129.

**Comment by Croakier** [comment]
Oh alright.

**Comment by seaweedchan** [comment]
>I'll continue it in the next release
>doesn't continue it in the next release

come on ihavenoface

**Comment by ihavenoface** [comment]
Obviously 2.37.9 was only to pump out this one fix.

**Comment by seaweedchan** [comment]
Still, changelog for everything. You link to the changelog in the settings, people use it.

**Comment by milkytiptoe** [comment]
Come on now. Don't get sloppy on the solid fork you've built.

**Comment by ididntknowicoulddothatXD** [comment]
ihavenoface, pls.
Pls.
Pls.
