### ISSUE TITLE
QR staying up after posting

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#135]
In a minimized state.
I use a 4chan Pass, by the way.

Anyway. Post goes through, QR gets smaller and stays like that unless I manually X it.
http://puu.sh/1OeRK

I want it to go away after posting, obviously.

**Comment by ihavenoface** [comment]
Anything in the console?

**Comment by ididntknowicoulddothatXD** [comment]
Uncaught TypeError: Cannot read property 'parentNode' of null script.js:476
$.extend.rm script.js:476
QR.response script.js:2904
callbacks.onload script.js:2812

**Comment by ihavenoface** [comment]
Looks like another thing with the Banchecker.
You can disable `Check for Bans` and `Check for Bans constantly` until I have taken a closer look at it.

**Comment by fit-bear** [comment]
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://sys.4chan.org/g/post". script.js:403
Uncaught TypeError: Cannot read property 'parentNode' of null script.js:476
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
XHR finished loading: "https://api.4chan.org/g/res/30745453.json". script.js:403
...

This happens to me.
Endless spamming of my Console and stuck QR.

**Comment by ihavenoface** [comment]
The script was trying to remove an element that isn't there at the moment. 8b51ceaae9fc07420297bfa10d641480e3fec4a6 will prevent this for now.

**Comment by ihavenoface** [comment]
Closing this. Please refer to #132 for this issue.
