### ISSUE TITLE
Almost every first captcha is told to be wrong

### ISSUE THREAD

**Issue by fit-bear** [ihavenoface/4chan-x#136]
Reproduction steps:

Lurk for some minutes.
Open QR
Type a comment and the captcha
Captcha is said to be wrong.
Reload
Still wrong
Reload
Still wrong
...
Works

Apparently, the captcha reload/reset timing is incorrect.

**Comment by ihavenoface** [comment]
I'm getting the same too but it doesn't feel like it's the timing. This might as well be the captcha just being retarded again.
