### ISSUE TITLE
Can't quote post numbers from non-thread updated posts.

### ISSUE THREAD

**Issue by MisakaImouto** [ihavenoface/4chan-x#139]
I've tried it with vanilla 4chan X from Mayhem and had no problem, so I'm submitting the bug here.
When you open a thread and try to click on a post number to quote them nothing happens. You can only do this successfully with posts that have been added by the thread updater.

**Comment by ihavenoface** [comment]
What version are you on?

**Comment by monkeyxmonkeyx** [comment]
Confirmed. Worked this morning before work. Back after work I can only quote posts added by the thread updater. 
Greasemonkey + ff 18 + 4chan X 2.37.8

**Comment by lowlymarine** [comment]
Confirmed with 4chanX 2.37.8 in all of the following browsers:
-Firefox Stable (18) + Scriptish
-Firefox Nightly (21) + Scriptish
-Chrome Beta (25)
-Opera 12.12
-Safari 6.0.2 + Ninjakit
On both Linux Mint 14 and OS X 10.8

**Comment by ihavenoface** [comment]
> 2.37.8

Well the latest version is 2.37.9 so you might want to update and report back.

**Comment by lowlymarine** [comment]
Ah, I can confirm that 2.37.9 works properly.  It's probably not worth filing its own bug report so I'll just mention it here: The install link at http://ihavenoface.github.com/4chan-x/#install still points to 2.37.8.

**Comment by ihavenoface** [comment]
Looks like for some reason it didn't push to stable, oh my. Thanks for the heads up.

**Comment by Teapsalm** [comment]
Broken with 2.37.9 for Pale Moon and Waterfox.

**Comment by ihavenoface** [comment]
@Teapsalm 
Although they should be the same as Firefox, Pale Moon and Waterfox aren't supported.
Anything in the console?

**Comment by ihavenoface** [comment]
Should point to stable now.
