### ISSUE TITLE
Quote Threading.

### ISSUE THREAD

**Issue by ihavenoface** [ihavenoface/4chan-x#14]

**Comment by ihavenoface** [comment]
https://github.com/ihavenoface/4chan-x/tree/quote-threading

**Comment by shiruse** [comment]
Quote threading works with that version, but I can't post a comment while signed in with 4chan pass. If quote threading can't be fixed for the current version, would it be possible to fix posting for the branch?

**Comment by ihavenoface** [comment]
Already done but not pushed to stable yet. One second.

14eb6654ad53521954189dbb318b2cb6342af576

**Comment by MaddoScientisto** [comment]
So what's the deal with this? 
Is there any chance of this ever being fixed?

**Comment by ihavenoface** [comment]
A chance sure, but no idea if I'll ever find the loop that doesn't stop looping.

**Comment by zixaphir** [comment]
I don't know how much you still care about this as this is a closed issue, but I fixed quote threading: https://github.com/zixaphir/appchan-x/compare/5d446e53be568f3f3ee7abff095c369bbd0d158d...QTv3

**Comment by MaddoScientisto** [comment]
That's great, I can't wait to see it working again, it's been so long

**Comment by ihavenoface** [comment]
@zixaphir 

> I don't know how much you still care about this

Not so much.
What about that weird raccess list, are you using that at all? That thing always tried to bite me by just looking at it.

**Comment by zixaphir** [comment]
Nope. Was, wrote it out.
