### ISSUE TITLE
Add the ``add the `show deleted posts' option'' option

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#140]
I know it's not first priority but will this eventually be added.

http://219.94.194.39/up/src/f10437.png

**Comment by ididntknowicoulddothatXD** [comment]
Deleted posts, as in, when there's a janitor going on a rampage, not /ghosting/.
Also, isn't that script dead?

**Comment by SweetLuv** [comment]
You mean like this?
https://fuuka.warosu.org/data/q/img/0004/31/1361253841053.png

If so, I would really want it. Please.

**Comment by ididntknowicoulddothatXD** [comment]
Yup, why it isn't implemented yet is beyond me.
