### ISSUE TITLE
Back linking not working

### ISSUE THREAD

**Issue by linklonk** [ihavenoface/4chan-x#142]
Back linking isn't working for some reason, I know it's not working for a couple of others as well.

**Comment by ihavenoface** [comment]
Anything in the console?
By backlink you mean what exactly?

**Comment by linklonk** [comment]
Hovering over the back links*
Sorry bout that

**Comment by ihavenoface** [comment]
As for my first question - please open the console as described here: http://ihavenoface.github.com/4chan-x/#bug-report and paste the output here.

**Comment by linklonk** [comment]
Turns out it was from 4chan's settings being enabled. Sorry for wasting your time.

**Comment by ihavenoface** [comment]
No problem.

**Comment by linklonk** [comment]
Wait, now youtube embeds aren't working

**Comment by linklonk** [comment]
Uncaught TypeError: Cannot call method 'addEventListener' of null extension-compiled.576.js:18
Uncaught TypeError: Cannot call method 'toLowerCase' of undefined script.js:5066

**Comment by ihavenoface** [comment]
Working fine on my end, but this doesn't seem relevant as I'm not using the method `toLowerCase()` on anything in the Linkifier.
Could you paste a screenshot of before and after clicking on [embed]?

**Comment by linklonk** [comment]
![embed](https://f.cloud.github.com/assets/3334149/88606/933a3f1e-64f5-11e2-9ed1-e5114e5b7622.jpg)

**Comment by ihavenoface** [comment]
This has been broken for a month now. Try updating to the latest version.

**Comment by linklonk** [comment]
It fixed it. I had re-downloaded from the site yesterday if that helps in the future. Thanks
