### ISSUE TITLE
Image expansion not working after Yotsuba update

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#143]
moot did: http://puu.sh/1RaeZ which is for mobile browsers.
This broke image expansion: http://puu.sh/1Re18

Console says nothing.

**Comment by ihavenoface** [comment]
Try https://github.com/ihavenoface/4chan-x/raw/master/4chan_x.user.js.

**Comment by ididntknowicoulddothatXD** [comment]
Thank you very very much, OP, I came on cat, etc.
