### ISSUE TITLE
Won't expand thumbnails upon clicking

### ISSUE THREAD

**Issue by LuckoftheIrish** [ihavenoface/4chan-x#144]
Issue was supposedly fixed in Mayhem's build, but those who don't want to use that build are having issues where expanding thumbnails cause the picture to minimize. The picture isn't 404'd, clicking on the filename opens the picture in another tab.

**Comment by ihavenoface** [comment]
#143

Also the new stable was pushed just seconds ago so you should be fine with just hitting update.
