### ISSUE TITLE
So, this just happened (Linkify)

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#145]
Might alert Mayhem, whatever.
http://puu.sh/1RgNz

Gonna sleep.
Post is here: https://boards.4chan.org/q/res/384986#p385691

**Comment by ididntknowicoulddothatXD** [comment]
https://boards.4chan.org/q/res/384986#p385710
xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by Tablecat** [comment]
http://boards.4chan.org/g/res/30924009#p30924326

lel

**Comment by ihavenoface** [comment]
Calling @Zixaphir
