### ISSUE TITLE
Clear image/file upload input without closing qr or refreshing the page.

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#146]
Firefox doesn't allow you to clean the upload/submission file field once an item has been selected, and the only way to reset the input is by refreshing the page. In the case of qr, you have to close it and re-open it to clear the image field, otherwise you're forced to upload something to your post.
I think it would be nice to have an option to clean or reset the image field so one doesn't have to refresh the page or re-open qr.

**Comment by milkytiptoe** [comment]
Shift+Click on the file input?

**Comment by ihavenoface** [comment]
Shift+click on `Choose File` did you try that?

**Comment by ihavenoface** [comment]
Closing for now. If this wasn't the function you were searching for, feel free to comment here.
