### ISSUE TITLE
Quote inline on board index

### ISSUE THREAD

**Issue by CrystalMoogle** [ihavenoface/4chan-x#148]
I remember having this feature a long time ago, maybe in an old version of 4chan X or maybe another extension I've forgotten about, but is it possible to add an option so that quote inline only affects the main index? As of right now, turning it on affects both board index and threads, which I guess some people like, but I'm not a huge fan. I always enjoyed having it on the board index, but I find it more annoying on the thread. It's not a huge deal since I've been without it for well over a year now, but it'd be nice to have.

**Comment by ihavenoface** [comment]
How about b58600ce642a79995adb6a088bb3a325e14994e7?

**Comment by CrystalMoogle** [comment]
That seems to be working perfectly, thank you~
