### ISSUE TITLE
Textcontent error on 4chan

### ISSUE THREAD

**Issue by ramenchef** [ihavenoface/4chan-x#150]
![Capture](https://f.cloud.github.com/assets/1252949/98437/2f050c66-6722-11e2-8347-18525dd9f63c.PNG)
Version 26.0.1386.0 dev-m Chrome
Tampermonkey 2.11.3007

**Comment by ihavenoface** [comment]
> now they are putting linebreaks on the end of each container

Who is responsible for this?

**Comment by ramenchef** [comment]
Not sure what you mean by that. I am using 4chan SS if that helps as well.

**Comment by ihavenoface** [comment]
Try ea9c7d4fffeda5129a49482faa258058ece6224e please.
http://boards.4chan.org/mu/res/32396968 would be a good example to test on.

**Comment by ramenchef** [comment]
Looks that that fixed what ever the issue was. Thanks.
