### ISSUE TITLE
Undefined instead of the quote

### ISSUE THREAD

**Issue by CrystalMoogle** [ihavenoface/4chan-x#151]
I noticed posts saying "undefined" instead of the post they were replying to (i disabled 4chan x to see what it was supposed to be).
I couldn't figure out what was the same in each post that was causing it, then I suddenly realised all of them had a link.
Also it doesn't seem to be affecting embedded links, only normal links.

Example: http://boards.4chan.org/v/res/173159967#p173160358

**Comment by ihavenoface** [comment]
Thanks for reporting.
Try b75ca06253a1f5d68f52bc024397e5171817499c, please.

**Comment by CrystalMoogle** [comment]
That seems to be working fine now, thanks again~
