### ISSUE TITLE
QR + 4chan Pass

### ISSUE THREAD

**Issue by SwaliLel** [ihavenoface/4chan-x#152]
I'm sooo tired of this.
This here is my QR: http://puu.sh/1T38d

As you can see, I block the Captcha. Now, I also use a 4chan Pass.
But I still have to put a random character in the Captcha box so it doesn't return a "No valid captcha." error every time before I post.
I don't know if this happens with other 4chan X users who use a pass but it's annoying. Can you make it an option to turn the Captcha off when I use a 4chan Pass?

**Comment by ihavenoface** [comment]
It should turn off _automagically_, but I don't really have the possibility to test anything related to the 4chan Pass.
@seaweedchan, does that happen to you as well?

**Comment by FishHeadswg** [comment]
You better buy a 4chan Pass then.

Do you want moot to starve on the streets or something?

**Comment by seaweedchan** [comment]
> @seaweedchan, does that happen to you as well?

Nope. 4chan X works fine with my 4chan Pass.

**Comment by vampiricwulf** [comment]
Works fine for me as well.

**Comment by ihavenoface** [comment]
Seems to be no issue on the scripts side then. Closing.
