### ISSUE TITLE
Add tumblr upload thingy

### ISSUE THREAD

**Issue by SwaliLel** [ihavenoface/4chan-x#153]
Instead of just having imgur and omploader, there should be a upload option that adds tumblr uploading on your blog.
Is this possible?

Pllllllllease?

**Comment by ihavenoface** [comment]
Just add in the appropriate URL maybe?

**Comment by SwaliLel** [comment]
I did it like
http://www.tumblr.com/share/photo?source=$2;text:tumblr
But it doesn't work.
URL I got that from: http://www.tumblr.com/share/photo?source=https%3A%2F%2Fi.canvasugc.com%2Fugc%2Fprocessed%2F92ed1a5bfae217939bd99bef9f0ee8bd56c30cf6.jpg%3Ftumblr&clickthru=http%3A%2F%2Fcanv.as%2Fs%2F1923x&caption=%3Cspan%20id%3D%22ugc_text_4%22%20class%3D%22ugc_text%22%3E%3C%2Fspan%3ERemix%20this%20image%20on%20%3Ca%20href%3D%22http%3A%2F%2Fcanv.as%2Fs%2F1923x%22%3Ehttp%3A%2F%2Fcanv.as%2Fs%2F1923x%3C%2Fa%3E.
or https://i.canvasugc.com/ugc/original/1a83082312e1a5b0dd1ab9105cf41d2a83467b2b.png

**Comment by ihavenoface** [comment]
Doesn't tumblr need authentication anyway? If that's the case this would be out of reach for this script.

**Comment by SwaliLel** [comment]
Got the problem.
How can I make it so it goes http://www.tumblr.com/share/photo?source=http%3A//images.4chan.org/b/src/1359288257192.jpg
instead of
http://www.tumblr.com/share/photo?source=http://images.4chan.org/b/src/1359288257192.jpg

Tried http://www.tumblr.com/share/photo?source=http%3A//$2;text:tumblr but it returns http://www.tumblr.com/share/photo?source=http%3A//https://images.4chan.org/b/src/1359288257192.jpg of course. What I need is to get the https: away.

**Comment by ihavenoface** [comment]
This would require the use of `encodeURI()`. Shouldn't be hard to add that as an option.

**Comment by SwaliLel** [comment]
Alright, thanks for helping me!

**Comment by ihavenoface** [comment]
Now that was a cute fix.
Try 71f3cc972a2cba1d5b04c452cca2ffddd1bbd485 please.

**Comment by SwaliLel** [comment]
http://tumblr.com/share/photo?source=$2;text:tumblr
works on both HTTP and HTTPS. Thank you~~
Can't wait for the next release.
