### ISSUE TITLE
"prev.data is undefined" on certain boards

### ISSUE THREAD

**Issue by FishHeadswg** [ihavenoface/4chan-x#154]
I'm getting this every time I open certain boards:

4chan X (2.38.3) error: prev.data is undefined

URL: http://boards.4chan.org/jp/
Linkify.node@chrome://scriptish/content/scriptish.js -> file:---/4chanx@aeosynth/4chanx@aeosynth.user.js:4901
Main.node@chrome://scriptish/content/scriptish.js -> file---/4chanx@aeosynth/4chanx@aeosynth.user.js:6618
Main.featuresReady@chrome://scriptish/content/scriptish.js -> file:---/4chanx@aeosynth/4chanx@aeosynth.user.js:6538
.ready/cb@chrome://scriptish/content/scriptish.js -> file:---s/4chanx@aeosynth/4chanx@aeosynth.user.js:352

Any idea what's going on here?

**Comment by ihavenoface** [comment]
Try updating to the [master](https://github.com/ihavenoface/4chan-x/raw/master/4chan_x.user.js) branch.

**Comment by FishHeadswg** [comment]
I was using the master branch. The issue seems to have disappeared on its own, though. No idea if it's fixed or not.

I'll go ahead and close this.

**Comment by ihavenoface** [comment]
The master branch won't update itself unless there's a higher version number which is equivalent to the stable and default version.
It is possible that you were not using this 3875587a9d31bc88d2cee0e1579a1a0145f8ad69 commit which was a fix related to this issue.
