### ISSUE TITLE
Filter question

### ISSUE THREAD

**Issue by SwaliLel** [ihavenoface/4chan-x#155]
Again, thanks for helping me the other day.
Now, I have another question.
How do I filter ANY thread (meaning OP, don't care about posts) on /q/ with "/int/" in the subject? (Fucking samefags)

Tried 
/^\/int\/$/;op:yes
to see if it works but this only filtered my test post that only had "/int/" in the subject, not the other threads.

**Comment by ihavenoface** [comment]
Try `/\/int\//g;op:yes`. Including `g` should be optional.

**Comment by SwaliLel** [comment]
Thank you, it worked!
