### ISSUE TITLE
"Deleting..." message stays for way too long.

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#156]
When I delete a file with the menu, the post is usually actually deleted as soon as I hit the button assuming there's no cooldown, yet it takes forever for "Deleting..." to change to "Deleted"

**Comment by ihavenoface** [comment]
Handling of the text content of that field should occur as soon as we get a valid response from the server though.

**Comment by seaweedchan** [comment]
Maybe indicate that? Its just weird now, it makes it look like its still in the process of deleting it when in fact its just in the process of checking that it deleted successfully.

**Comment by ihavenoface** [comment]
As in 'Waiting for response...', or?

**Comment by seaweedchan** [comment]
Maybe like 

"Delete File" <- Click
"Deleted!" then after a second:
"Checking..."
"Success!"

**Comment by milkytiptoe** [comment]
Why would you say 'Deleted' when you can't be sure it's deleted yet this is stupid

**Comment by ihavenoface** [comment]
I was about to write that.

**Comment by seaweedchan** [comment]
Why would you say deleting when its already been deleted? Checking !=
deleting

Frankly I don't even understand the need to check. If you don't know which posts you made you're probably retarded

**Comment by ihavenoface** [comment]
> Error: Password incorrect.
> [Return]

**Comment by seaweedchan** [comment]
> Password incorrect
> 
> password

You're not serious, are you? Please don't be serious. There's a reason the password field was removed from the quick reply.

**Comment by ihavenoface** [comment]
This happens on IP change.

**Comment by seaweedchan** [comment]
So the menu needs to inform people that they ban evaded? How silly.

**Comment by ihavenoface** [comment]
How is changing your IP in every way related to bans though?

But whatever. The check is what we will get in every way from the server, so why not use it?

**Comment by seaweedchan** [comment]
Then make the message actually relevant to what its doing.

If its deleting, say deleting.
If its checking, say checking.
If it says deleting but its actually checking, that's bad design.

**Comment by milkytiptoe** [comment]
I am actually speechless
