### ISSUE TITLE
<wbr> please respond

### ISSUE THREAD

**Issue by SwaliLel** [ihavenoface/4chan-x#157]
http://puu.sh/1Yz5R

Chrome, console:
Port error: Could not establish connection. Receiving end does not exist. miscellaneous_bindings:236
Uncaught TypeError: Cannot call method 'addEventListener' of null extension-compiled.596.js:18
Port error: Could not establish connection. Receiving end does not exist. miscellaneous_bindings:236

**Comment by SwaliLel** [comment]
<span class="quote">&gt;&gt;<a href="https://www.4chan.org/faq#banappe" target="_blank">https://www.4chan.org/faq#banappe</a><wbr>al</span>

Please respond. <wbr> again.

Console:
Uncaught TypeError: Cannot call method 'addEventListener' of null extension-compiled.596.js:18

**Comment by ihavenoface** [comment]
See #124.
