### ISSUE TITLE
latest 2.38.3 broken in locked threads

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#158]
everything looks as if 4chan X weren't installed in locked threads (like the ones at /q/)

Error: TypeError: el is null
Source File: chrome://scriptish/content/scriptish.js -> file:///C:/Users/lel/AppData/Roaming/Mozilla/Firefox/Profiles/j98jsh28.4chanx/scriptish_scripts/4chanx@aeosynth/4chanx@aeosynth.user.js
Line: 477

**Comment by ihavenoface** [comment]
Probably 4chan being retarded again. Closing.
