### ISSUE TITLE
Stupid AdBlock copy

### ISSUE THREAD

**Issue by SweetLuv** [ihavenoface/4chan-x#159]
Holy shit, I'm so fucking mad right now, I could break something.
Now, I don't want to sound rude, but what the fuck.

Apparently the current 4chan X version copies AdBlock behavior and removes the ads for some reason. I personally tested it, I disabled it in Chrome and suddenly the ads were all there, again.

Now, I personally wouldn't have a problem with it, BUT.

Whenever I enter a thread it also removes the "Posting Mode: Reply" thing. Basically, it looks like this (http://puu.sh/2271I) in threads now. This doesn't happen when disabling 4chan X and using AdBlock.

Can you, or whoever the hell is/was responsible for this, remove the AdBlocking-feature or get it to somehow show the "Posting Mode"?

Thanks,

Anon

**Comment by ihavenoface** [comment]
Why does the removal of a useless red bar make you mad?

I can make the cleanup optional if you want.

**Comment by ihavenoface** [comment]
Actually I removed its removal completely as it is easy the remove it with EHHA or whatever. The hrs always have been a pain though.

See 9a909499fe0d94f0d13abab6a9d8741fc3ce3e92.
