### ISSUE TITLE
Script stops working in closed threads

### ISSUE THREAD

**Issue by SweetLuv** [ihavenoface/4chan-x#160]
Check it out: https://boards.4chan.org/q/res/427404#p427404

**Comment by ihavenoface** [comment]
Seems to work fine for me.
What does not work for you? Anything in the console?

**Comment by SweetLuv** [comment]
Uncaught TypeError: Cannot read property 'parentNode' of null script.js:478

**Comment by ihavenoface** [comment]
This doesn't really tell me anything.

Though if my guess is correct, installing [this](https://github.com/ihavenoface/4chan-x/raw/stuff/4chan_x.user.js) will give a better output.

**Comment by SweetLuv** [comment]
It DOES work for some reason now. Thanks.

What did you do, though?

**Comment by ihavenoface** [comment]
![dunno](https://f.cloud.github.com/assets/1175752/165373/7bd24394-7940-11e2-934a-e0d90d54cfb7.png)

Dunno.

**Comment by ihavenoface** [comment]
Updated the testing [branch](https://github.com/ihavenoface/4chan-x/raw/stuff/4chan_x.user.js) again.
Please let me know if that works.

**Comment by SweetLuv** [comment]
Yes, it works.
