### ISSUE TITLE
Name indicator

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#164]
Would it be possible to append a little symbol or text saying (You) after the name if you posted from the QR?

Pic related. http://puu.sh/26pA0
That would be the best way, actually.

Please, it would be so good, especially in larger threads and if you don't use a tripcode regularly.

**Comment by ihavenoface** [comment]
~~Done in master.~~

Whoops.

**Comment by ihavenoface** [comment]
I think that adding (You) to the header would take up too much space.
How about something like a red (or orange) line?

![22](https://f.cloud.github.com/assets/1175752/227612/2a94026e-8666-11e2-8b40-c3289ebe04d1.png)
