### ISSUE TITLE
4chan X v3 discussion

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#166]
@ihavenoface, do you have any idea of what changes you'll be adopting and which you'll be changing?

I think for me every new change aside from those that are objectively better should be made optional. The fixed bar? Not a fan, would never work with my userstyle and I'd love a way to disable it, and yet it could still be made useful and work well with the Custom Navigation Links.

Quick reply link gone? I'd love an option to have that back. it's much more useful to me than having a link tucked away.

The v3 menu that drops down underneath the arrow clicked on the top bar could instead go under the normal 4chan x link that your fork now already has.

Your current keybinds are also much better than v3's.

**Comment by ihavenoface** [comment]
This is a little hard to say when it's not ready yet.

**Comment by fit-bear** [comment]
I'd say to simply clone v3 repo and re-add (writing it optimized just like Mayhem did) prefetch images, classic thread updater, etc.
