### ISSUE TITLE
Allow 4chan posters to communicate with spirits

### ISSUE THREAD

**Issue by fit-bear** [ihavenoface/4chan-x#169]
https://userscripts.org/scripts/show/74489

**Comment by ihavenoface** [comment]
What's the purpose of posting random scripts on the issue-tracker?

**Comment by vampiricwulf** [comment]
He probably wants you to implement the script in yours, which I believe you should not as that script would be a stupid feature.

**Comment by ihavenoface** [comment]
Seconding.

**Comment by fit-bear** [comment]
The feature I suggest to be implemented is "Allow 4chan posters to communicate with spirits", i.e. show deleted posts and ghost posts on 4chan. Here is a mock-up: ![](http://i.imgur.com/XtcsA.png)

The userscript I posted in a _very_ old broken one, that practically doesn't work any more (but have the source available, which can help you in development of this feature).

Sorry for the confusion, should have been clearer.

**Comment by vampiricwulf** [comment]
Did mayhem not do that in v3? I thought he did.

**Comment by fit-bear** [comment]
No, he didn't.

**Comment by ihavenoface** [comment]
![2](https://f.cloud.github.com/assets/1175752/197305/55dc14e6-8037-11e2-9362-4508dbecf5b7.png)

I wouldn't see how that script would do it any better than this solution.

**Comment by fit-bear** [comment]
In that,
1. Someone must quote the deleted post for you to see it exists
2. Posts done in archives aren't shown
3. There is no cute ghost ![cute ghost](http://img35.imageshack.us/img35/347/ghostwhite.gif)

**Comment by ihavenoface** [comment]
> There is no cute ghost ![](http://img35.imageshack.us/img35/347/ghostwhite.gif)

I will see what I can do.

**Comment by fit-bear** [comment]
Only about the cute ghost or also about the other 2 things?

I think those'd be great additions...

**Comment by vampiricwulf** [comment]
>noface's priority being the cute ghost. 
Too funny.

**Comment by fit-bear** [comment]
Posts done in the archives can have the cute ghost and deleted posts a trash can.

Even though I still prefer cute ghost for everything. Perhaps two colours for them?
