### ISSUE TITLE
Depaging/Rolling ala 2009

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#170]
Today, I found a little but effective script.
https://gist.github.com/enumerator/5037125

I am amazed by this script, it literally shows every thread there is. And its one that works in this current age and time.

Now, there is only 1 problem.
After 15 or so threads, it stops working with 4chan X, meaning no QR, dropdown not working, no thread expansion, etc. on the index and everything.

Would it be possible to either

> modify 4chan X to display its features on all pages when the linked script is used

or

> modify the depaging script so it works with 4chan X

or

> add a working depage feature to 4chan X, in no relation to the script I linked

Why this would be good:

> Threads that don't get noticed due to being not on the first few pages will get more posts in them and eventually discussions might start again.
> 
> rule violating threads on the other pages can be reported by users encouraged
> 
> more...?

Inb4: Catalog. The Catalog is a dumb retarded feature and only a small part of the text/current replies is visible. You also cannot QR on the same page to bump threads, reporting is impossible. You can't compare the catalog to viewing threads.

**Comment by seaweedchan** [comment]
This would just make it very resource heavy as all depaging scripts do.

**Comment by vampiricwulf** [comment]
How about altering catalog so that when you click on it a preview appears like underneath OP posts on the regular pages? It will only be resource heavy if you click on every single thread in catalog.

**Comment by popman** [comment]
@seaweedchan It depends on how the depaging is done. It shouldn't be any heavier than adding new posts through the API.
Ideally you'd give the user options to limit the grabbing.
I can see issues with faster boards though.

**Comment by seaweedchan** [comment]
>responding a month later

put your tripcode back on, ihavenoface :3

**Comment by zixaphir** [comment]
We could depage from JSON,

https://api.4chan.org/g/threads.json

by loading the JSON on page load and filling threads as the user scrolls down... (to maintain the state and not have to do multiple API requests in a small timeframe)

**Comment by ihavenoface** [comment]
@zixaphir
Sounds like a sane idea but depaging is still somewhat controversial. Personally I wouldn't want to use it.

**Comment by ihavenoface** [comment]
Closing as the catalog is now quite alright.
