### ISSUE TITLE
Request: (You) on quotelinks of posts you made

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#171]
Both AppChan X and the default extension have implemented this. When I'm Anonymous its harder to follow threads without it.

**Comment by vampiricwulf** [comment]
:+1:

**Comment by ihavenoface** [comment]
"Done in v3.".

**Comment by vampiricwulf** [comment]
:nose: :point_left: Laughed. (On the nose.)

**Comment by seaweedchan** [comment]
v3 is yuck and far away, can't we implement it now~

**Comment by ihavenoface** [comment]
It's late so here's only a rough version which won't do anything fancy like saving your array for refresh yet.

77629d56a039f6635920bf148aff2dbd9039c6cd

**Comment by milkytiptoe** [comment]
> hurr

Lol

**Comment by ihavenoface** [comment]
Should I store by board or is the reference for thread number enough?

edit: 549b626757f28e29e2264132f73078b83a7217b0 seems to be almost cool by now. Please test, etc..

**Comment by seaweedchan** [comment]
Seems fine as it is now, I'll use it while at work regularly too

**Comment by ihavenoface** [comment]
Rewrote it and it's in master now.

**Comment by ihavenoface** [comment]
> name

Can be confused with admin / developer / special snowflakes.

How about lowering the opacity:
![24](https://f.cloud.github.com/assets/1175752/230035/d146bb38-86b1-11e2-9fa4-29d3ec89d8aa.png)

**Comment by ihavenoface** [comment]
Then I'm going to keep that for now until someone comes up with something better.

**Comment by ihavenoface** [comment]
![25](https://f.cloud.github.com/assets/1175752/230101/91c9fd74-86b3-11e2-8367-e3cc31a99a40.png)

Too visible imo.

**Comment by vampiricwulf** [comment]
Why not use an emoji or something of the like?
