### ISSUE TITLE
Request: Exporting/Importing of Filter preferences

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#172]
Similar to the new exporting/importing of the 4chan X settings, this would make it easier share filters with others or across different computers.

One way you could do it is to have it create the preference list by dividing the sections with comments, like

-Click Export and the list is generated like this:

```
# Name *
/^Ulrik Munther$/
/^EdgarAllenDerp$/
/^isac$/
/^Peerless$/

# Tripcode *
/^!MyImoutol6$/
/^!!0MEI\/Dc6cPC$/
/^!Kawaii07ec$/

# * Do not remove these comments to ensure settings are properly imported.
```

Sections that are empty or contain only comments would be left out entirely for readability. 

I reposted this issue on Mayhem's fork as well.

**Comment by ihavenoface** [comment]
Mayhem will do that apperently. Closing.
