### ISSUE TITLE
Rule linking

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#176]
Can this be please implemented.

http://puu.sh/2bD3Y

**Comment by ihavenoface** [comment]
Yes. Thanks for the suggestion.

**Comment by vampiricwulf** [comment]
:+1:

**Comment by ididntknowicoulddothatXD** [comment]
Thanks, noface~

**Comment by ihavenoface** [comment]
Uhm what?

**Comment by vampiricwulf** [comment]
Why'd he close it and thank you when you haven't even done it yet?

**Comment by ihavenoface** [comment]
![mystery](https://f.cloud.github.com/assets/1175752/239944/224137aa-88e4-11e2-872a-4e4f6e4ba5f1.gif)

**Comment by ididntknowicoulddothatXD** [comment]
Is this done or aborted?

**Comment by ihavenoface** [comment]
I might reopen it when I find the time. Which is unlikely.
