### ISSUE TITLE
Prefetch Images Checkbox in the way

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#18]
![](http://puu.sh/190Sp)
Covers 4chan Sound Player.

**Comment by seaweedchan** [comment]
Not a 4chan X issue

**Comment by vampiricwulf** [comment]
I meant the check box blocks the 4chan sound player button. Sorry for the confusion. 
Or is Oneechan placing them that way?
Sorry, not at home, rushing around and typing on my phone.

**Comment by seaweedchan** [comment]
It is, and I just changed it.

**Comment by vampiricwulf** [comment]
Oh okay, sorry.
