### ISSUE TITLE
Thread doesnt update on post

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#19]
;_;

**Comment by vampiricwulf** [comment]
Wasn't there also an issue for this on Mayhem's? 
Also +1, would be nice to finally not have to press the key bind every time I post. 
Found it:
https://github.com/MayhemYDG/4chan-x/issues/440

**Comment by seaweedchan** [comment]
The issue was that the post doesn't appear as soon as you post but I don't understand why it can't just wait 2 seconds and update.

**Comment by ihavenoface** [comment]
Works for me.

`return setTimeout(Updater.update, 500);`

You could also just put in another update in chain if 500ms isn't enough to fetch the post. 
Y/N?

**Comment by seaweedchan** [comment]
Setting it to 1000 seems to have done the job nicely.

Nightly + 4chan Pass.

**Comment by ihavenoface** [comment]
c9c1f4cb101df99f6464a91d8c11973ea34233aa

Maybe I'll manage to come up with something more fancy than this, but here you go.

**Comment by seaweedchan** [comment]
<3

**Comment by ihavenoface** [comment]
~~66f62b657ed8feffc07b09927713b2c5b3f84f19~~
184372113333e21918b4831ba389070083668450

This is probably terrible and inefficient, but please test.
