### ISSUE TITLE
Add menu item to force reload image.

### ISSUE THREAD

**Issue by popman** [ihavenoface/4chan-x#190]
Images occasionally dick out and only load half way, especially when auto-gif is turned on and the only way to load the rest of it is to open in a new tab and append a ? to the end.

This would save a ton of trouble for anyone with a shitty connection, or when the server is wigging out.

**Comment by ihavenoface** [comment]
Refer to https://github.com/ihavenoface/4chan-x/issues/191#issuecomment-24483519.
