### ISSUE TITLE
Exception options for replacing thumbnails.

### ISSUE THREAD

**Issue by popman** [ihavenoface/4chan-x#191]
Add options to disable replacing thumbnails with the full image under certain conditions.

e.g. "Replace thumb of GIFs (unless; thread is 85% images or image is >3.5MB)" "Replace thumb of PNGs (only if image is <1500x4000 (Could also use <1500*4000 for less than 6Mp))

I'm suggesting this because I currently get lockups on my shitty computer after stumbling into a thread that's all GIFS or high res PNGs and have to turn it off.

Kind of like how other forks of this script disable it on /gif/ (for different reasons)

**Comment by ihavenoface** [comment]
> and have to turn it off

As you should.
Image Replace is a bad feature. I'm not even sure why I ported it to v3 in the first place.
