### ISSUE TITLE
(You) coming up on posts I never made

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#196]
http://puu.sh/2lSVw
https://boards.4chan.org/gd/res/22807#p23439

4chan X claims this is my post. I replied to it to see what happens and it displays as >>23439 (You). This is an error as I never made this post using 4chan X. I share a network but no PC. Pls fix.

**Comment by ihavenoface** [comment]
I can see how this happens.
Just to verify, please open a console (on 4chan), drop 
`JSON.parse(localStorage.getItem('4chan_x.yourPosts'))[22807]` 
in it and give me the output.

**Comment by ididntknowicoulddothatXD** [comment]
It says 
["23439", "23789"]

**Comment by ihavenoface** [comment]
Alright, thanks.

**Comment by ididntknowicoulddothatXD** [comment]
K.

**Comment by ihavenoface** [comment]
Last commit _should_ have fixed it. Please test, etc..
