### ISSUE TITLE
Broken threads!

### ISSUE THREAD

**Issue by Vafarien** [ihavenoface/4chan-x#197]
During posting and auto updating the thread doubles over by re-adding post starting from op all over again doubling the post count as undefined shown here
![broken](https://f.cloud.github.com/assets/2349950/294111/5d236276-93d4-11e2-9b7e-909683200bed.JPG)

**Comment by ihavenoface** [comment]
Noticing this as well but it only happens too sporadically. I'll keep an eye on it though.
Thanks for reporting.

**Comment by Vafarien** [comment]
Good luck in destroying it!

**Comment by ihavenoface** [comment]
Looks like it's 4chan being dumb. I'll leave this open until they get it together.

**Comment by Vafarien** [comment]
Save us noface!

**Comment by ihavenoface** [comment]
Looks like they have fixed it. Does it still happen on your side?

**Comment by Vafarien** [comment]
Its been a good while with no issues, thank you noface.
