### ISSUE TITLE
favicon keeps showing "new post" icon after scrolling to bottom

### ISSUE THREAD

**Issue by jikot** [ihavenoface/4chan-x#198]
so the favicon keeps showing the "new post" icon after scrolling to bottom

usually the favicon will change to the "no new posts" icon after three new replies

refreshing the page helps in some cases, but not always

using regular chrome with win7 if that's relevant

**Comment by jikot** [comment]
the tab also shows (1) or (2) no matter how hard i scroll to the bottom

as i said usually the tab will show the correct indicators after three new posts or so

**Comment by ihavenoface** [comment]
According to upstream this is a bug in chrome and there's no real fix for it yet.

**Comment by jikot** [comment]
Doesn't happen with the mayhem fork.

**Comment by Vafarien** [comment]
using noface fork and chrome and win 7

not seeing this issue. maybe try adjusting your settings?

**Comment by ihavenoface** [comment]
This should be done with v3. Closing.
