### ISSUE TITLE
Customization of posting's fields

### ISSUE THREAD

**Issue by zunbar** [ihavenoface/4chan-x#2]
Creation of a new tab on 4chan X' Settings
A "Fields" tab.

On the following, a menu is presented in which you can select default fields you will use for each board.

For example, you could do:

/jp/ : Name:blank Subject:blank Email:sage
/h/ : Name:#isj3s Subject:blank Email:blank
/w/: Name:blank Subject:blank Email:blank 
/wg/: Name:blank Subject:blank Email:blank
/y/: Name:blank Subject:blank Email:blank etc.
Perhaps a wildcard, so you could set just 2 boards you want customized, and the rest to "blank"

Reminder:

1) Setting to blank is different than not setting anything. Setting to blank means that, even if you manually use a name, subject or email, next time you post, everything will be "forgot". It will be back to "blank". Differently than 4chan's default behaviour that remembers email and subject

**Comment by seaweedchan** [comment]
Frankly if this were implemented I'd switch in a heartbeat over to ihavenoface x.

**Comment by vampiricwulf** [comment]
I think it would be easier to use and nicer to see if it was set like the Custom Navigation Links (from 4chan SS and Oneechan) where you only have to add the boards you want to do anything specific with.

**Comment by ihavenoface** [comment]
Looking over CN this would be fairly easy to implement without having to add more bloat.

**Comment by Poilaucul** [comment]
That would be great, I remember 4Chan Plus for Chrome had something similar but not as elaborated as OP's idea.

**Comment by ihavenoface** [comment]
e898d043b926d0e57633b8aec228ffff6ecd05d9
