### ISSUE TITLE
Background updater timers

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#20]
I kinda got use to Mayhem's update timer and I actually think the growing timer while in the background is a good idea. 
Mind making an option to enable increasing background timers? Maybe make them customizable as well, though stock is fine with me, no need for bloat if you don't want it.

**Comment by seaweedchan** [comment]
People have requested this since that4chanwolf's fork first appeared. Dunno why it hasnt happened.

**Comment by ihavenoface** [comment]
Please test.

79e4a66f60344d36f7b6c1604c38d11c5aebfd54

**Comment by vampiricwulf** [comment]
![](http://puu.sh/19tMh)
The alignment is a little weird.

**Comment by ihavenoface** [comment]
> OneeChan in charge of alignments

**Comment by vampiricwulf** [comment]
Guh, sorry, keep forgetting, running a test in the background, seems to be working perfectly, going to try out optional timer now, might eb nice to make them custom (giving them their own page between Keybinds and Rice.)

**Comment by vampiricwulf** [comment]
Optional increase doesn't seem to be working.

**Comment by vampiricwulf** [comment]
Woops.

**Comment by ihavenoface** [comment]
Try the latest commit.

**Comment by vampiricwulf** [comment]
Yep, works now! Thank you!

**Comment by ihavenoface** [comment]
> might eb nice to make them custom

I'll look into that.

**Comment by ihavenoface** [comment]
8c58fae23f7d0fb1cb86b833cae913439c36ff97

**Comment by vampiricwulf** [comment]
It works! Thank you again!
Just something I noticed, the preview for the unread favicons has disappeared, also reminding you that you named it `Test here:`, in case you forget.

**Comment by ihavenoface** [comment]
> the preview for the unread favicons has disappeared

~~Because I wrapped the favicons in ul and now the selector fails. Oh well.~~

Because I forgot to include the span element.

**Comment by vampiricwulf** [comment]
Your variables for the timers must be backwards, because background is determining the active window's timers

**Comment by vampiricwulf** [comment]
Found it: c21b4c10e45a076c5fc17145c3c5ea475b13d6fc

**Comment by ihavenoface** [comment]
Fixed.
Anything else you had in mind for this or is this good as is?

**Comment by vampiricwulf** [comment]
Is there a way to allow as many increments as possible?
I currently have it `1,2,3,4,5,6,7,8,9,10,15,20,25,30,60,90,120,180,240,300`
but since your script only allows 10 increments it only does `1,2,3,4,5,6,7,8,9,10`

**Comment by ihavenoface** [comment]
No idea whether I'm walking in the right direction, but here goes
06120135ad65ad12830345a025eb8235d3110c6a

**Comment by vampiricwulf** [comment]
"NaN"

**Comment by vampiricwulf** [comment]
Couldn't you turn the input box into a string and tell the conf to read the string as if it were an array? (Could just be spouting utter shit, I did something somewhat similar to make a round about program on my calculator.)

**Comment by ihavenoface** [comment]
Just giving Math.max a number works too - the comma was too much.

87a33337a773956ec0e02a6277c1fd84cbace52e

**Comment by vampiricwulf** [comment]
Still only goes to 10, don't get why though.

**Comment by ihavenoface** [comment]
Turns out that Math.max has a maximum of numbers to compare.
Well at least it's somewhat more automated. Maybe I'll manage to bake the whole thing together with this.

**Comment by vampiricwulf** [comment]
I'll just smile and nod since it sounds like what you said made your life somewhat easier.

**Comment by seaweedchan** [comment]
`[15:59:26.376] Empty string passed to getElementById(). @ file:///C:/Users/seaweed/AppData/Roaming/Mozilla/Firefox/Profiles/1woxbz3u.jo/gm_scripts/4chan_x/4chan_x.user.js:346`

**Comment by ihavenoface** [comment]
Not related to this.

**Comment by seaweedchan** [comment]
It looked like it was in the updater section, but either way now you know~

**Comment by ihavenoface** [comment]
The same thing has been logged for some time actually and I still don't know what it is causing it. Apparently it doesn't hurt the script though.
