### ISSUE TITLE
4chan X 3

### ISSUE THREAD

**Issue by DumpAnon** [ihavenoface/4chan-x#200]
Will you publish a "uncensored" version of v.3 that has 1 second refresh rate and all the other stuff that Mayhem was forced to remove...? Pls respond.

**Comment by ihavenoface** [comment]
https://github.com/ihavenoface/4chan-x/commit/3c8f11897ccf9293ea4b6f98a8ae59e031a633c8#commitcomment-2817590

**Comment by ididntknowicoulddothatXD** [comment]
Please make sure to include your Linkifier (with YT, etc.) and the old up and down buttons. They don't exist anymore, apparently. Really annoying if you're in the middle of a thread and just want to go down.

Also, bringing back the navigation bar at the bottom would be nice. It was removed..

**Comment by vampiricwulf** [comment]
How's V3 progress going?

**Comment by milkytiptoe** [comment]
> No v3 branch

Take a guess

**Comment by seaweedchan** [comment]
It probably won't happen. That'd take effort.

**Comment by ihavenoface** [comment]
@seaweedchan 
Suspending you for now.

**Comment by ihavenoface** [comment]
https://github.com/ihavenoface/4chan-x/tree/v3

**Comment by vendethiel** [comment]
yay~

**Comment by ididntknowicoulddothatXD** [comment]
Wubwubwub.

**Comment by vampiricwulf** [comment]
Thanks noface. Sorry for always asking so much of you.

**Comment by DumpAnon** [comment]
Where can I find the link to download your version?
I'm new to this stuff, sorry.

**Comment by ihavenoface** [comment]
@DumpAnon 
Under [builds](https://github.com/ihavenoface/4chan-x/tree/v3/builds). (4chan-X.user.js for Firefox/Gecko / 4chan-X.js for Opera/Presto).
Just click on the one you need and then on raw, this should give you the install dialog.

Chrome extension is [here](https://chrome.google.com/webstore/detail/4chan-x/gnhjbjalndahpllcacfkbjddcclhadpi).

> I'm new to this stuff, sorry.

This is not a problem.

**Comment by DumpAnon** [comment]
Thank you, it worked! (Using Chrome)

Can I make a request here? I like the new way the navbar works. Can you make it follow you again? Or add an option?

**Comment by ihavenoface** [comment]
I'm still playing around with it mostly. Objective is to have it lock on top of the page instead of completely hiding it.

**Comment by ididntknowicoulddothatXD** [comment]
I really don't like that v3 forces you to open a thread in a new tab when you reply to it from the index.

Any chance of changing that?

**Comment by vampiricwulf** [comment]
Sage Keybind please.

**Comment by ihavenoface** [comment]
> Any chance of changing that?

Try disabling
`Open Post in New Tab: Open new threads or replies to a thread from the index in a new tab.`?

> Sage Keybind please.

What do you want it to be mapped as?

**Comment by vampiricwulf** [comment]
I use `ctrl+s`, if Submit is conflicting, I tend to use `ctrl+Enter` for submit.

**Comment by ididntknowicoulddothatXD** [comment]
http://puu.sh/2BkQ0
This looks ugly.

Happens when hiding the global message.

> Try disabling: Open Post in New Tab

Oh, didn't notice that. Thank you. And sorry I request so much. Really appreciate your work.

**Comment by vampiricwulf** [comment]
Is it just me or are the fields in Rice always empty? (prefs are still saved, but it's always empty after a refresh. They show up on MayhemV3.)

**Comment by ihavenoface** [comment]
@amidoinrite 

> This looks ugly.

Yeah no idea how he screwed that up. The catalog also still shows the native hiding button.

@vampiricwulf 
What version of X are you using? This happened for me as well on an earlier one but now it seems to works fine.

**Comment by vampiricwulf** [comment]
`3.1.4`, (ahahaha π) Maybe it's just on my side? I'm going to create a new profile real quick and try that way.

**Comment by vampiricwulf** [comment]
Nope, new profile didn't solve it. I'm using straight from v3/build.

**Comment by ihavenoface** [comment]
I can dig around a little but I doubt I will find anything to resolve this.
With fields you mean every field, yes?

**Comment by vampiricwulf** [comment]
Found the root of the error, turn off Custom Navigation to reciprocate.
It's in MayhemV3 as well, so this is an issue for him too.
Made an issue on his repo.
He says he's on it.
Looks like he fixed it.

**Comment by ihavenoface** [comment]
Oh right I re-enabled that at some point.

**Comment by vampiricwulf** [comment]
Maybe at this point you should make V3 the default branch.

**Comment by ihavenoface** [comment]
Why though?

**Comment by vampiricwulf** [comment]
Because you're putting more focus in to V3 rather than v2.

**Comment by smcdude** [comment]
A couple of things:

Are you going to re-add the option to select which archive you want to use for boards with more than one?

Are you going to re-add the "Remember Sage" option?

**Comment by ihavenoface** [comment]
Yep. Though this needs to be rewritten.

We have (and had) personas with 61ed26c913baff2ae2ba9729fcbec6b8c9573ae9, you might want to check that out.

**Comment by nstepien** [comment]
> Yep. Though this needs to be rewritten.

I'll probably do it during this week-end, just thought you should know.

**Comment by ihavenoface** [comment]
I'll stay tuned, thank you.
