### ISSUE TITLE
Integration of new archives

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#201]
Inb4 Woxxy changes it back.

https://archive.foolz.us/gd/
https://archive.foolz.us/mlp/
https://archive.foolz.us/vp/
https://archive.foolz.us/vr/

**Comment by ihavenoface** [comment]
Thanks.
Do they have full images?

**Comment by ididntknowicoulddothatXD** [comment]
They all seem to support full images, except /mlp/.

**Comment by ihavenoface** [comment]
Alright. I can't test if this works right now so you might want to and report back.

**Comment by ididntknowicoulddothatXD** [comment]
> so you might want to and report back.

When clicking /vp/'s dropdown menu there's no "archive" link.

**Comment by ihavenoface** [comment]
Works fine on my end.

**Comment by ididntknowicoulddothatXD** [comment]
Huh. 
I can confirm it works when using HTTP. If you're on HTTPS it doesn't.
Imported the settings on both to sync them but the error still exists. No HTTPS Archive link.

**Comment by ihavenoface** [comment]
Cannot reproduce on https either (and it shouldn't make a difference). Sorry.
