### ISSUE TITLE
Quick reply box keeps disappearing off the screen

### ISSUE THREAD

**Issue by hithertounknown** [ihavenoface/4chan-x#203]
I know that it is not completely gone because I can still post blind, but I cannot see what I am writing. This issue only seems to happen on my laptop, perhaps because its screen is really small (1024 × 600). I'm not sure how it happens, or how to get it back.

Firefox 19.02
4chan X 2.38.6

**Comment by ihavenoface** [comment]
Positioning should have changed with v3. Feel free to leave a comment should this still occur.
