### ISSUE TITLE
Error Like a Ghost

### ISSUE THREAD

**Issue by ScrapBone** [ihavenoface/4chan-x#204]
Hello gents. Im having some odd issue with the script not working to the point it didn't show at all. First it was simple gone, leaving the 4chan's default script in it's place on the site but the default script wouldn't open either.The script still redirected any 404'dimages and threads but still had no presence on the site. This was while running Firefox 19.0.2. Deleting,restarting the browser, and reinstalling the script didn't help but after updating to Firefox 20 the 4chan X button replace the settings one but the menu for wont open and it still only redirects 404'd things. I hadn't thought of opening the console till just then but here's what I found.

Error: [4chanx@aeosynth] TypeError: parent is null
Source File: file:///C:/Documents%20and%20Settings/Owner/Application%20Data/Mozilla/Firefox/Profiles/fghn6r74.default/scriptish_scripts/4chanx@aeosynth/4chanx@aeosynth.user.js
Line: 538

Error: TypeError: $.id(...) is null
Source File: http://static.4chan.org/js/extension-compiled.623.js
Line: 24

this was with to a few other things but those are the only ones that had glaring red ERROR signs on them.

Thank you for any help in advance.

**Comment by ihavenoface** [comment]
Uninstall Scriptish.
Install Greasemonkey.
Report back.

**Comment by ScrapBone** [comment]
It works. Thanks but could you tell me what happened with scriptish?

**Comment by ihavenoface** [comment]
Nothing happened with it. It's dead.
