### ISSUE TITLE
Faulty auto-updater in latest commits

### ISSUE THREAD

**Issue by anonomoo** [ihavenoface/4chan-x#208]
Starting exactly from commit c6c1dc25b33d18acc8d90e1ea4ad936d340989b4 ("Add desktop notifications.") the auto-updater stopped working.
Firefox 20, GM stable, Ganoo plus linux.

**Comment by ihavenoface** [comment]
9b68d782ce19c23c452cb372c6d6a1425861a342

**Comment by anonomoo** [comment]
I've tried commit 9b68d782ce19c23c452cb372c6d6a1425861a342, doesn't seem to fix it.

**Comment by ihavenoface** [comment]
> Firefox 20

It works on Nightly only as it says in the description.

**Comment by anonomoo** [comment]
I've missed the part where it's said that it works on Nightly only, it seems.
Any chance for the Fx stable channel?

**Comment by ihavenoface** [comment]
Whenever they push [Bug 594543](https://bugzilla.mozilla.org/show_bug.cgi?id=594543) to stable, sure.

**Comment by anonomoo** [comment]
Thank you for the reference. Closing.
