### ISSUE TITLE
4chan x v2.38.8 inactive

### ISSUE THREAD

**Issue by LuckoftheIrish** [ihavenoface/4chan-x#210]
Discovered that the add-on can't do anything. It shows [4chan X settings] but the link won't activate. Threads won't refresh and it generally acts as though the script isn't even there.

Tried removing and reinstalling but no luck.

**Comment by ihavenoface** [comment]
You've been using Nightly, right?

**Comment by LuckoftheIrish** [comment]
I've been using the stable. I've tried it on scriptish and on GreaseMonkey. GreaseMonkey just completely doesn't work for any of my scripts.

Scriptish just has issues with your 4chan x

**Comment by ihavenoface** [comment]
First of all, please ditch Scriptish.
Second it would be a little hard to trace the error with no output which I guess isn't there.

Please try starting Firefox with a new and seperate profile to see if it works at all.

**Comment by LuckoftheIrish** [comment]
I already completely restarted firefox, guess there was something wrong with the GreaseMonkey installation that just wouldn't get removed when I tried to uninstall the script myself.

**Comment by ihavenoface** [comment]
> completely restarted firefox

This isn't what I mean by new profile.
http://kb.mozillazine.org/Profile_Manager

**Comment by LuckoftheIrish** [comment]
I had already taken the step before you suggested the new profile, on Hu's advice

Sorry

**Comment by ihavenoface** [comment]
I suppose there's nothing else to check for then, I'm sorry.

**Comment by LuckoftheIrish** [comment]
I think it wasn't the script, it was on my end. Sorry about that, guess I just jumped to conclusions :T
