### ISSUE TITLE
Archivers

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#213]
Old shit, again.

http://archive.4plebs.org/ /hr/
https://www.xn--clich-fsa.net/4chan/cgi-board.pl/e/ /e/

**Comment by ihavenoface** [comment]
Thank you.

**Comment by hithertounknown** [comment]
https://fuuka.warosu.org/fa/ /fa/

**Comment by ididntknowicoulddothatXD** [comment]
It also has /s4s/, if that hasn't been added yet.

**Comment by popman** [comment]
http://loveisover.me/
For /h/,/d/ and /v/

Please add to V2 also.
