### ISSUE TITLE
Thread Watcher not working properly

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#215]
-> Try to add/delete threads from the watcher doesn't work.

× /mlp/ - MLP General
× /mlp/ - Equestrian Adventure - Part 'Temporarily on Hold'
× /mlp/ - Anonymous
× /mlp/ - MLP General
× /mlp/ - MLP GENERAL
× /q/ - RP threads on /vp/
× /v/ - How is she so perfect, /v/?

-> Deleting first thread removes last thread

× /mlp/ - Equestrian Adventure - Part 'Temporarily on Hold'
× /mlp/ - Anonymous
× /mlp/ - MLP General
× /mlp/ - MLP GENERAL
× /q/ - RP threads on /vp/

-> Deleting another thread

× /mlp/ - MLP General
× /mlp/ - Equestrian Adventure - Part 'Temporarily on Hold'
× /mlp/ - MLP General
× /mlp/ - MLP GENERAL
× /q/ - RP threads on /vp/

-> And again

× /mlp/ - Equestrian Adventure - Part 'Temporarily on Hold'
× /mlp/ - Anonymous
× /mlp/ - MLP General
× /mlp/ - MLP GENERAL
× /q/ - RP threads on /vp/

-> Re--adding /v/ thread

× /mlp/ - MLP General
× /mlp/ - Equestrian Adventure - Part 'Temporarily on Hold'
× /mlp/ - Anonymous
× /mlp/ - MLP General
× /mlp/ - MLP GENERAL
× /q/ - RP threads on /vp/
× /v/ - How is she so perfect, /v/?

-> Refresh unwatches the latest thread

Console: 
Error during storage.set: This request exceeds the MAX_SUSTAINED_WRITE_OPERATIONS_PER_MINUTE quota. sendRequest:22
chromeHidden.handleResponse sendRequest:22

Trying to unwatch the /v/ thread brings this up:
Uncaught TypeError: Cannot convert null to object script.js:6556
(anonymous function) script.js:6556
chromeHidden.handleResponse

**Comment by ihavenoface** [comment]
https://github.com/MayhemYDG/4chan-x/issues/1018
`Uncaught TypeError: Cannot convert null to object script.js:6556` is probably something different though.

Thanks for reporting.

**Comment by ihavenoface** [comment]
Closing as the Thread Watcher will get a rewrite.

**Comment by ididntknowicoulddothatXD** [comment]
Hooray.
