### ISSUE TITLE
Linkify Plus integration?

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#22]
Kind of like AppChan X does, but based on Linkify Plus rather than Mayhem's.

http://userscripts.org/scripts/review/1352

**Comment by zixaphir** [comment]
Out of curiosity, what advantages does that linkify plus have over Mayhem's?

**Comment by seaweedchan** [comment]
Updated more frequently, and I don't really like Mayhem.

**Comment by ihavenoface** [comment]
> Porting a whole userscript

Since you won't really gain anything from that, does it really matter having LP running as a second one?
Last time I checked LP couldn't linkify multiple lines so I'd rather put in 4chan Linkify or 4chan hyperlinks anyway.

**Comment by seaweedchan** [comment]
If you don't want other userscripts integrated into 4chan X, I suggest you remove the /b/ackwash elements like quote preview, inlined quotes, cross-thread and OP indicators -- and the entire thread updater. These were integrated into 4chan X for a reason.

> couldnt linkify multiple lines

Eh? Works here.
<img src="http://i.imgur.com/hOiMp.png">

**Comment by ihavenoface** [comment]
I didn't say I don't want, I said that you wouldn't gain anything.
Integrating isn't just taking something external and slapping it on that other thing. /b/ackwash, etc. clearly has more intergration than what would come when I would start throwing a standalone script at it.

**Comment by seaweedchan** [comment]
> Integrating isn't just taking something external and slapping it on that other thing.

Then what's the issue? That's clearly not what I'm requesting after all.

I would gain one less userscript to have to use, and not having to edit it to make it 4chan-only after every update, and you would gain less users moving to AppChan X.

**Comment by ihavenoface** [comment]
> Works here.

With multiple lines I mean long links, not multiple links which 4chan tends to cut off.

> That's clearly not what I'm requesting after all.

It is. Remember what fork you are on.

Anyway, see
~~https://github.com/ihavenoface/4chan-x/pull/21#issuecomment-9007637~~

> but based on Linkify Plus rather than Mayhem's

Forgot about that. It can't be helped then.
Maybe I'll 'integrate' it, I don't know yet.

**Comment by ihavenoface** [comment]
> not having to edit it to make it 4chan-only after every update

Why not do this?
http://img6.imagebanana.com/img/ih0tq7cp/snapshot8.png

**Comment by zixaphir** [comment]
On a side note, appchan x now supports multi-line links.

**Comment by ihavenoface** [comment]
I wouldn't mind a pull request then.

**Comment by zixaphir** [comment]
Was working on one, but I can't get your options menu to open. Might be my fault, trying to trace the source of the issue.

**Comment by ihavenoface** [comment]
76268a784cc861d12c115051d5468c8dadbed6ff

**Comment by zixaphir** [comment]
Doesn't seem to be related.
