### ISSUE TITLE
Scroll to Last Read Post... or not

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#220]
> Scroll to Last Read Post

Not working; if it's boards.4chan.org/board/thread and not */thread#post it scrolls back to the last post. Terrible if you come back to the thread using the Thread Watcher.

Sorry if this sounds rude.

**Comment by ihavenoface** [comment]
Works fine on my end. Which version of 4chen X are you on?

> Sorry if this sounds rude.

?

**Comment by ididntknowicoulddothatXD** [comment]
K. I'm using v3.3.1 and I disabled said option.

Go to https://boards.4chan.org/vr/res/589872 and watch it. Leave after ~50 posts and go to the index. Then go back to the thread using the Thread Watcher. Even if disabled it seems to scroll back to the latest post.

> ?

Thought it sounded too demanding.

I think it's because the link in the TW is https://boards.4chan.org/vr/res/589872 and not https://boards.4chan.org/vr/res/589872#p589872

**Comment by ihavenoface** [comment]
Can't reproduce and I doubt it's closely related to the script.
If you'd like I could append `#pThreadnumber` as a temporary fix.

**Comment by ididntknowicoulddothatXD** [comment]
Yes, please, it would mean much to me.

**Comment by ihavenoface** [comment]
Please try that. Not sure if you will need to rewatch the thread.

**Comment by ididntknowicoulddothatXD** [comment]
Sorry, was away, works as expected.
