### ISSUE TITLE
(Re) Thread Watcher

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#221]
Removing a thread (https://boards.4chan.org/q/res/588806, in this case) gets this:
Error during storage.set: This request exceeds the MAX_SUSTAINED_WRITE_OPERATIONS_PER_MINUTE quota. sendRequest:22

Adding it back creates this:
Error during storage.set: This request exceeds the MAX_SUSTAINED_WRITE_OPERATIONS_PER_MINUTE quota. 

Removing it and going to the index/somewhere else brings the thread back.
Adding another thread creates this:
Error during storage.set: This request exceeds the MAX_SUSTAINED_WRITE_OPERATIONS_PER_MINUTE quota. sendRequest:22

I don't get it, I just want to remove a thread and keep ones I added.

**Comment by ihavenoface** [comment]
That's an issue with Chrom*. You can wait a bit (PER_MINUTE?) and try removing it again.

**Comment by milkytiptoe** [comment]
https://github.com/MayhemYDG/4chan-x/issues/1018
