### ISSUE TITLE
Linkification bug

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#222]
https://boards.4chan.org/mlp/res/10531425#p10558919

Linkifies text that isn't a URL.

https://boards.4chan.org/mlp/res/10561251
Check the format of this one. Go to the native archive to compare.

**Comment by ihavenoface** [comment]
> Linkifies text that isn't a URL.

Fixed with 2c3cdaad94ff6ebe90611c5200e688462e373987. Turns out I was a bit too generous with catching as much valid results as possible.

> Check the format of this one.

Will be fixed.
