### ISSUE TITLE
In a long list of filters, ctrl+F freezes Firefox.

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#225]
I have a very long list of about 250 images filtered in the md5 field. Sometimes I need to check if there's a duplicate entry so I press ctrl+F. This instantly freezes the browser without the search bar even showing up and I have to restart it. This didn't happen in 4chan X 2.x at all.

I'd also like to suggest a feature. In 4chan x 2.x the default action when filtering a reply was to hide replies only and not OP's, but this has changed, now I have to manually add ;op:no to almost all the entries already in the md5 list, and I have to manually type it every time I add a new entry, which happens frequently. I wondered if there's a chance to add an option in 4chan X to allow users to choose default settings to add when filtering something via the drop-down menu in posts, like in 4chan X 2.x when filtering something in the original post it automatically added ;op:yes at the end of the string.

**Comment by ihavenoface** [comment]
> This instantly freezes the browser without the search bar even showing up

Can't reproduce. Try with a clean profile maybe?

> I wondered if there's a chance to add an option in 4chan X to allow users to choose default settings to add when filtering something via the drop-down menu in posts

Sounds like a good idea. Will look into it.

**Comment by usernamestring** [comment]
Thanks for considering my suggestion.
About the freezing problem, I'm sorry, I made a mistake, the number of entries in my md5 filter list is actually 57,139. I tried with a new Firefox profile with only Greasemonkey and 4chan X installed, copied and pasted the md5 filter list to the new profile, and doing ctrl+F while the filter list is open still freezes the browser. 

Here's a link for the full md5 list in case you want to use it to test or reproduce the problem.

http://www.mediafire.com/view/eu23e1znlnddm6k/test.txt

**Comment by ihavenoface** [comment]
> the number of entries in my md5 filter list is actually 57,139.

![1327873024324](https://f.cloud.github.com/assets/1175752/549021/460f3c22-c2f0-11e2-87fd-7c307baeb609.jpg)

**Comment by usernamestring** [comment]
I know it's a very long list, but I had no problem with previous 4chan X versions. There was a noticeable but short delay when switching to the md5 section list, and scrolling through it sometimes felt a little sluggish, but only sometimes, that's all, and had no problem using ctr+F.
I really hope there is a way to fix it without having to lower the number of entries in the list.
