### ISSUE TITLE
Update the archive links for V2

### ISSUE THREAD

**Issue by Croakier** [ihavenoface/4chan-x#226]
You don't have to maintain V2 if you don't want to, but can you at least update the archive redirection links, particularly for /v/ and /vg//.

**Comment by ihavenoface** [comment]
Sure, but what let's you stay with the last version?

**Comment by Croakier** [comment]
I'm not quite sure what you mean by that. But 4chan X v3 removed to many features and doesn't work properly with Oneechan. So right now I'm on 2.38.8.
