### ISSUE TITLE
Can't import settings after system restore

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#229]
Today I had a fatal crash while uninstalling a program and I had to do a system restore. My system works properly now but every time I refresh 4chan, the 4chan X settings menu comes up, clear.
So I tried to import my previous settings but 4chan X can't overwrite them, although it states that the import was successful.
I then tried to manually set up my preferences but that failed as well.

> Console
> 
> Uncaught TypeError: Cannot read property 'boards' of undefined script.js:1661
> (anonymous function) script.js:1661
> done script.js:623
> chromeHidden.handleResponse sendRequest:67
> Uncaught TypeError: Cannot read property 'boards' of undefined script.js:1676
> (anonymous function) script.js:1676
> done script.js:623
> chromeHidden.handleResponse sendRequest:67

I am using the latest Chrome, which is 27.0.1453.110 m, apparently., Windows 7 and my system was restored to a day earlier. I didn't use my PC this weekend, except Sunday evening, and the restore point was Sunday evening.

https://github.com/MayhemYDG/4chan-x/issues/1145 Related; works if I try Chromium instead. 4chan X v2.38.8, however, is working just fine.

**Comment by ihavenoface** [comment]
Nothing I can fix, sorry.

**Comment by ididntknowicoulddothatXD** [comment]
You know what could cause it, though?
