### ISSUE TITLE
More customizable Custom Board Navigation list

### ISSUE THREAD

**Issue by Halsey1006** [ihavenoface/4chan-x#231]
I'm trying to organize my Custom Board Navigation list so I have normal boards on the first line, and porn boards on the second line, but to do that I have to add filler to the first line to force the second to fill out with just the porn boards. It'd be great if I could just \n for a new line.

**Comment by ihavenoface** [comment]
Sounds like an interesting idea. Please try that commit.

**Comment by Halsey1006** [comment]
Works perfectly, thanks for the addition.
