### ISSUE TITLE
J / K navigation keybinds.

### ISSUE THREAD

**Issue by valtism** [ihavenoface/4chan-x#235]
Well I love v3 of 4chan X, really bought a much needed simplification of settings to the table. That said, I would like some more freedom with the keybinds. Having J and K to navigate up and down threads on the front page of a board seems like a very intuitive keybind to have, and one I used a lot in v2.

If you don't think it's necessary, that's ok, but it is one feature I'd love to see back in v3.

Thanks

**Comment by ihavenoface** [comment]
If you still want this, feel free to comment here.
