### ISSUE TITLE
Incompatibility with lazarus form recovery in QR.

### ISSUE THREAD

**Issue by popman** [ihavenoface/4chan-x#237]
The add-on for Firefox, Lazarus form recovery can not recover the post form in QR when multiple posts are queued.
Each queued post is treated like a revision and only the last one is saved.
This could be solved by treating each queued post as a different text entry form. (though that's way too much of a headache, so an in-house solution or workaround would probably work better.)

**Comment by ihavenoface** [comment]
Might want to take a look at https://addons.mozilla.org/en-us/firefox/addon/its-all-text.
