### ISSUE TITLE
Auto-break long posts.

### ISSUE THREAD

**Issue by popman** [ihavenoface/4chan-x#238]
Add an option to break posts over 1500 characters into multiple posts. With breaks either at the double linebreak, single linebreak, or full-stop followed by a space/linebreak nearest to the character limit.
Using [/BR] as a manual override point for post breaking would save a lot of hassle.

Broken posts from a thread starting post should be submitted to the new thread in stead of breaking and attempting to post on the index.

**Comment by ihavenoface** [comment]
I'm not interested in parsing the input when you can use a simple editor before making posts.
