### ISSUE TITLE
Linkify

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#24]
Blank Spoiler tag.

**Comment by ihavenoface** [comment]
> Ctrl-click

It's Ctrl + shift + click though. What do you propose instead?

**Comment by vampiricwulf** [comment]
The inclusion of Shift doesn't change it sadly, and I can't propose anything since it seems that when I change it the function still doesn't work.

**Comment by ihavenoface** [comment]
Does 4chan Linkify fork for you?

**Comment by vampiricwulf** [comment]
Never tried, give me a second.
Do you mean Mayhem's LinkifyPlusFork?

**Comment by vampiricwulf** [comment]
Mayhem's LinkifyPlusFork doesn't work for me, but the official LinkifyPlus userscript does.

**Comment by ihavenoface** [comment]
I mean http://userscripts.org/scripts/show/87750 - whether the keybind does work or not.

**Comment by vampiricwulf** [comment]
Nope, the keybind, even without changing it, doesn't work for me.

**Comment by vampiricwulf** [comment]
It definitely does take over the keybind from its original action, but it doesn't fix the links.
testing it with tiny url on http://boards.4chan.org/a/res/72270320

**Comment by vampiricwulf** [comment]
This would explain it
http://userscripts.org/topics/114072
But he said he fixed it in his new version...
The pastebin version does fix the tinyurl being cut in half issue though.

**Comment by vampiricwulf** [comment]
I have no skill with this stuff, but w.e. the guy on the right did is correct and the left is wrong when it comes to links split by spoiler tags.
**Non-expired link:** http://diffchecker.com/P44Tw34O

**Comment by vampiricwulf** [comment]
I did a proper test, Spoiler broken links do not work, but the keybind does fix links that 4chan splits into the next line, though it does also open up my context menu, would Shift+Alt not be a viable substitute?
Also do please look at the link posted in my previous comment and fix the spoiler broken links.

**Comment by vampiricwulf** [comment]
Edit: Fuck I'm stupid.

**Comment by vampiricwulf** [comment]
It doesn't work at all with Shift+Ctrl but works as supposed to with Shift+Alt and since it remaps keybinds shift+alt doesn't have any retardation like shift+ctrl.

**Comment by ihavenoface** [comment]
To conclude this, you would like to:
1. Change the keybind from S+C to S+A and
2. Want the text after a spoiler not appending fixed.

Right / Not right?

**Comment by vampiricwulf** [comment]
Right.

**Comment by ihavenoface** [comment]
8c197673ae2c5745ea86ced0e8a65eb6d38f6177 should do for now.
Needing two keys to concat the link is stupid anyway. I'll think of something for adding spoilers automatic later.

**Comment by vampiricwulf** [comment]
Works great!

**Comment by ihavenoface** [comment]
Now we regard blank spoiler tags in links.
3d8e0cd939626a5fc5c89175960b76d979fdda6e

Please test.

**Comment by vampiricwulf** [comment]
Seems to work great.

**Comment by ihavenoface** [comment]
Looks like there's still some problems with some kinds of formatting.

**Comment by ihavenoface** [comment]
This occurs when someone inserts two or more spoilers (Why didn't I think of testing for that?), see http://boards.4chan.org/vg/res/17873989 for reference.

![blank](http://i.imagebanana.com/img/xrz63gb0/20121106121230_1600x900_scrot.png)

I'll revert the change for now.

**Comment by ramenchef** [comment]
Hrm. Just happened again in 2.36.5

http://i.imgur.com/UpAIt.png

**Comment by vampiricwulf** [comment]
2.36.5? I think that's a bigger issue, the versioning is off. A thread link would be nice.

**Comment by ramenchef** [comment]
https://boards.4chan.org/a/res/74637052

There you go.

**Comment by vampiricwulf** [comment]
Nothing wrong on Nightly, other than the current huge Nightly bug, if setting up chrome from step -1 wasn't such a pain, I'd try to reproduce.

**Comment by ihavenoface** [comment]
I was yet again not cautious enough. Now I'm actually checking for both elements before and after the spoiler tag for actual text before smashing them together so hopefully there won't be any errors from that direction anymore.
https://boards.4chan.org/a/res/74637052 works with no problem so far.

**Comment by vampiricwulf** [comment]
Looks like blank spoiler tags are cutting links again. <3~
![ilu.](http://i.imgur.com/xT7oqX0.jpg)

**Comment by ihavenoface** [comment]
See #124. No idea when I have time to rewrite it.

Also blank spoilers don't exist anymore as 4chan nukes them.

**Comment by vampiricwulf** [comment]
Ah, thanks.
Buyfaggers now `[spoiler].[/spoiler]` for their tinyurl business.
