### ISSUE TITLE
Why is this allowed? (Linkify)

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#240]
https://boards.4chan.org/mlp/res/12223265#p12223265

> Don't forget to visit our main pastebin here http://pastebin.com/GSDzCC5U [Embed]] or our website here http://www.mymassivepony.com/

http://puu.sh/3HoOQ.png

"or our website here" links to mymassivepony.

**Comment by ihavenoface** [comment]
Looks like an error, indeed. Will be fixed with the new parser once the pending pr is done.
Nice name btw..

Thanks for reporting.

**Comment by ihavenoface** [comment]
Fixed. Will be in the next version.
