### ISSUE TITLE
Text isn't cleared from quick reply and conflics with other tabs

### ISSUE THREAD

**Issue by MaddoScientisto** [ihavenoface/4chan-x#242]
Firefox Aurora and 4chanx 4.5.0, happens on two different computers with similar configurations.

SOmetimes when I have multiple tabs with multiple threads open and I post into a thread in one the text doesn't get cleared from the quick reply window.

Afterwards if I post into another thread in another tab, after it's done posting if I return to the previous tab in which I posted earlier I get a "no valid captcha" error as if I had just tried to post on that tab as well.

**Comment by ihavenoface** [comment]
Should be fixed as of now.
Feel free to comment again if it is not.
