### ISSUE TITLE
Chrome keeps installing 3.4.10

### ISSUE THREAD

**Issue by linklonk** [ihavenoface/4chan-x#245]
From the stable build at http://ihavenoface.github.io/4chan-x/

Also I can't find any way to turn on archives for /v/

Sorry for being a bother

**Comment by ihavenoface** [comment]
> Draft Version 3.5.0

~~Should be fixed soon.~~

> Also I can't find any way to turn on archives for /v/

Should be added back now. Try hitting `Update now` in the Archive dialog.
