### ISSUE TITLE
Prevent images from expanding in quick preview and inline replies

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#246]
When using 'Expand all images", images contained in quick preview and inline replies remain expanded.
In the case of inline replies with images, the image is expanded again every time the quotelink gets clicked, even if the image within the original reply has been contracted manually.
In the case of quick preview there is no way to contract the expanded image within it. This happens even with filtered posts if they get inlined or quick previewed.
Can this be fixed or is there a way to prevent this behavior?

**Comment by ihavenoface** [comment]
Can't reproduce. Probably has been fixed already.
