### ISSUE TITLE
Changing cookie behaviour freezes hidden threads list

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#247]
Changing cookie preferences to "Keep cookies until I close Firefox" (changing value network.cookie.lifetimePolicy from default 0 to 2) "freezes" the hidden threads list and every time the browser is started, the list resets itself to the last state it was right before the preference was changed, previously hidden threads will remain hidden next session even after being unhid manually, newly hidden threads will remain visible. Manually clearing the hidden threads list in main 4chan X options does nothing.
I'm using Firefox 22

**Comment by ihavenoface** [comment]
You seem to be having problems with Firefox altogether. You might want to try a new profile.
