### ISSUE TITLE
Clicking "embed" link inside inline post takes you to the content page in same tab.

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#248]
Normally if you click the "embed" option in a media link it embeds the content, clicking the video title opens the content page in a new tab.

But if you click any portion of a linkified media link contained in an inline reply it will always take you to the content page within the same tab it was clicked on.

Also embedding of pastebin links seems to be broken, clicking "embed" displays an empty frame.

**Comment by ihavenoface** [comment]
This is a known issue, or rather a part that has not been written yet.

> Also embedding of pastebin links seems to be broken, clicking "embed" displays an empty frame.

Works fine on my end. Care pointing to the post where this is happening?

**Comment by usernamestring** [comment]
It happens with all pastebin links. I just noticed this in the error console:

Error: Blocked loading mixed active content "http://pastebin.com/embed_iframe.php?i=6C43SnP6"
Source File: gm_scripts/4chan_X/4chan-X.user.js
Line: 460

Keeps happening even on firefox 23.0 fresh install with clean profile, only Greasemonkey + 4chan X.

**Comment by ihavenoface** [comment]
Likely you're browing 4chan with https enabled. Try reproducing this with just http or tell Firefox not to block mixed content.

**Comment by usernamestring** [comment]
It's true.
Embedding pastebin links on http://boards works, https://boards doesn't.
A feature enabled by default in Firefox 23 was preventing pastebin embedding from https (security.mixed_content.block_active_content)
