### ISSUE TITLE
"Polyfill" initialization crashed.

### ISSUE THREAD

**Issue by FishHeadswg** [ihavenoface/4chan-x#249]
```
"Polyfill" initialization crashed.
TypeError: undefined has no properties
```

Fix this shit, nerd.

**Comment by ihavenoface** [comment]
Update your Firefox instead?

**Comment by FishHeadswg** [comment]
Normally I would deck your scrawny ass for taking that tone with me but since it fixed my problem I'll let you off the hook this one time.

Don't let it happen again.
