### ISSUE TITLE
Minor request: Thread summary on index

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#251]
> - 8 posts omitted.

It looks a bit empty, especially if there are no image replies. Could this please be changed to

> - 8 posts omitted. Click here to view.

?

**Comment by ihavenoface** [comment]
> 273 posts and 65 image replies omitted. Click here to view.

Now it's somewhat long, don't you think?

**Comment by ididntknowicoulddothatXD** [comment]
http://puu.sh/43XKa.png

> > Comment too long. Click here to view the full text.
