### ISSUE TITLE
Drop down menu in quick reply box for selecting flag on /pol/

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#253]
Is it possible to add /pol/'s new drop down flag selection menu in the quick reply box?

Also is it possible to add a password field to the quick reply box when starting a new thread? When on board pages there is no way to choose a deletion password if the original post form is hidden (default) unless one changes settings temporally and reloads the page.

**Comment by ihavenoface** [comment]
> Also is it possible to add a password field to the quick reply box when starting a new thread?

See the description in the QR tab in the settings.

**Comment by ihavenoface** [comment]
Build is at https://ihavenoface.me/builds/4chan-X.user.js.
Please test.
