### ISSUE TITLE
Duplicate file exists: upload next image

### ISSUE THREAD

**Issue by Poilaucul** [ihavenoface/4chan-x#255]
Hello, when duplicate file exists is it possible to ad an option to upload the next image instead of stopping the uploading?
Is it also possible to increase the cooldown beetween each posts?

**Comment by ihavenoface** [comment]
What if you're in the process of dumping a series of images?

> Is it also possible to increase the cooldown beetween each posts?

I wouldn't see a use for it, personally. Why would you want that?

**Comment by Poilaucul** [comment]
> What if you're in the process of dumping a series of images?

In that case it would be nice to have a checkbox to specify whether or 4chan X should ignore duplicate file errors and post the next image.
Or posting a link to the duplicate image would be another solution too, since it's would be impossible to post the duplicate image as long as the original one is up anyway.

> I wouldn't see a use for it, personally. Why would you want that?

On slow boards 30seconds between posts is just too fast I think, sometimes I dump sets in thread A and post replies in thread B and it's impossible to do that with 4chan's cool down without suspending sets dumping.

**Comment by ihavenoface** [comment]
The option is visible in the dump list of the QR.
The current timeout, when a duplicate is detected, is 10 seconds.
Please test. The builds are on the install page.
