### ISSUE TITLE
Timer for reporting posts.

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#256]
Would it be possible to add a cooldown timer to the "Report this post" menu, similar to the post deletion one, that would grey out the report link until the timer runs out and you're allowed to make a new report?
I think this would be useful because sometimes there is rule breaking content being posted quite fast and the only way to get mods' attention is by reporting every single one of the bad posts. I'm concerned when there's illegal content being spammed.
I think the waiting time is 15 seconds. I also believe (I'm not 100% sure) that if you accidentally attempt to report a post before the waiting time runs out, it still counts as if you had reported something, and you get the "You have already reported enough posts" warning sooner, but I'm not completely sure about this.

I would also like to know if it's possible to add links from #navtopright to the custom navigation bar ([Settings] [Rules] [FAQ] [Feedback] [Status] [Home]).

Thank you in advance.

**Comment by ihavenoface** [comment]
> I'm not 100% sure

Then you should test this thoroughly and report back.

> I would also like to know if it's possible to add links from #navtopright to the custom navigation bar

I guess it is.

**Comment by ihavenoface** [comment]
Closing until you have the timeouts.
