### ISSUE TITLE
Pin/Make Thread Watcher Scroll with Page

### ISSUE THREAD

**Issue by mothe** [ihavenoface/4chan-x#257]
I'd like to request an option to pin the thread watcher to page, in a similar fashion as v2 with the sidebar. It makes accessing watched threads much easier as you don't have to look for it or go back to the top of the page each time.

**Comment by ihavenoface** [comment]
There was a sidebar in v2?

**Comment by mothe** [comment]
I thought there was by default, but I always used stylescript/oneechan in combination with your 4chan-x fork

**Comment by ihavenoface** [comment]
That was a stylesheet thing.
You can use

```
#thread-watcher {
  position: fixed
}
```

in the CSS field of the Rice section in the Settings to have the Thread Watcher scroll along.
