### ISSUE TITLE
Search image by md5 doesn't work in /b/'s archive.

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#258]
Searching for files by md5 hash in the archive menu doesn't work if the hash contains the slash symbol (/). Unlike other archive sites, worldathleticproject replaces the slashes in the url with underscores (_).

**Comment by ihavenoface** [comment]
Thanks for reporting.

Also @MayhemYDG.

**Comment by nstepien** [comment]
That's caused by an improperly configured server it seems.
MD5 searching doesn't seem to work on /b/ in worldathleticproject anyway.
@Proplex
http://stackoverflow.com/questions/4390436/need-to-allow-encoded-slashes-on-apache
>end of 2013
>Apache

**Comment by ihavenoface** [comment]
I see.
[MD5 search in general](http://fuuka.worldathleticproject.org/b/search/image/jF%2BQLWweT1kS34zW68jxcw%3D%3D) looks fine to me.

**Comment by nstepien** [comment]
Mmh, the first picture I found didn't seem to work though:
http://fuuka.worldathleticproject.org/b/thread/510278891/#510287409
Whatever!

**Comment by davidlohle** [comment]
This issue was fixed, thanks for pointing it out.

```
>2013
>not using apache with MPM and 1500 processing server threads
```

The apache boxes each have 3770's and 32GB of RAM. I feel like wasting resources.

Proof here: https://fuuka.worldathleticproject.org/b/search/image/D%2Fw%2B1W4U7y1pkED9DvuHEQ%3D%3D

**Comment by nstepien** [comment]
I don't know about resources, but isn't nginx supposed to be stronker?

**Comment by davidlohle** [comment]
Now that I'm archiving a ton of boards, the traffic increase might prompt me to switch to nginx.

I only have about 50 active visitors given at any moment. When shit hits the fan, like the 500,000,000th get on /b/, I had about 300 active vistors with about 75 page requests a second--a far cry from a heavy load. If I need be, and the users start pouring in, I'll then start to prompt software changes.
