### ISSUE TITLE
Backlink pyramid bug

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#26]
![](http://i.imgur.com/XduIA.png)
![](http://i.imgur.com/jnJvB.png)
Proof that oneechan isn't at fault:
![](http://i.imgur.com/hSHuM.png)
![](http://i.imgur.com/nkzi9.png)

**Comment by ihavenoface** [comment]
Out of curiosity - how often do you link back that far back? I've noticed that too but didn't think of it as being too much of a problem.
Thanks for reporting though (for the other reports too). I'll look into that when I have the time.

**Comment by vampiricwulf** [comment]
I only go that far if a quoting happens to go that far, so rarely. And no problem, I like helping when I can.

**Comment by ihavenoface** [comment]
I haven't looked into the backlink function itself yet but it looks like only Firefox has a problem with stacking up that much classes. Chromium handles this with no problem.

**Comment by vampiricwulf** [comment]
Sounds like we have to wait on FFx to fix it then. Is there any pre-existing bug report on this?

**Comment by ihavenoface** [comment]
> Sounds like we have to wait on FFx to fix it then.

Note that there's a high possibility of me being wrong.

**Comment by vampiricwulf** [comment]
Unrelated question, what do you plan on doing when v3 comes out? Will you try be able to reimpliment from old code or will you have to rewrite everything as well?

**Comment by ihavenoface** [comment]
Depends on how v3 will look like. The parts I have written personally (read: not much) will be translated easily.

**Comment by vampiricwulf** [comment]
Is there any other way to align the quotes without the tacking on of classes? (other than threading, did you drop that btw?)

**Comment by ihavenoface** [comment]
Sure there is. One only has to find it without breaking other things.

> (other than threading, did you drop that btw?)

I didn't drop anything but because I don't use threading and never will I won't put effort in trying to fix it.

**Comment by ihavenoface** [comment]
Doubt I'll ever get to fix this.

**Comment by vampiricwulf** [comment]
Okay ;_;
![](http://puu.sh/1AAHi)

**Comment by ihavenoface** [comment]
Just don't go _too far_ and it'll be alright.
