### ISSUE TITLE
Move hidden threads to bottom on board pages.

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#261]
Is it possible to add an option for placing hidden and filtered threads to the bottom of board pages? Something similar can be achieved by highlighting all threads that remain unfiltered, the downside is that threads manually hidden remain in their original place on board pages.

I'd also like to know if there's a way to stop 4chan X from embedding Youtube links. I want to keep embedding enabled for all other sites (soundcloud, pastebin etc) I just need to disallow youtube links.
Is there something I can add or comment out within the source code to achieve this?

Thank you in advance.

**Comment by ihavenoface** [comment]
Maybe when https://github.com/MayhemYDG/4chan-x/pull/1316 is done.

Search for `name: 'YouTube',` in the script. I'm sure it's obvious what needs to be deleted.

**Comment by usernamestring** [comment]
Thank you very much.

**Comment by ihavenoface** [comment]
Actually, you can just hide the stubs as well.
