### ISSUE TITLE
Keybinds: Jump to page0 broken

### ISSUE THREAD

**Issue by daisuke-asao** [ihavenoface/4chan-x#262]
4chan X 3.9.0
Browser: Chrome 30.0.1599.101 m

Jump to page0 broken most likely due to the implementation of refresh index introduced in 3.9.0. Nothing happens when the key is pressed for Jump to page0.

My workaround is to bind the key to refresh index. I'd say that jump to page0 has become abundant but that is not for me to decide.

**Comment by ihavenoface** [comment]
![screen shot 2013-11-06 at 15 10 38](https://f.cloud.github.com/assets/1175752/1482917/3e2938b0-46ed-11e3-87c2-7156a810315a.png)

**Comment by daisuke-asao** [comment]
I have index mode set to "Paged" and not on "All threads" if that is what you meant.

Since 3.9.0, "jump to page0" does nothing when you are already on page0, I have just found now that it would do the jump when you are browsing a thread or a different page. Before 3.9.0 used it to refresh page 0, not just the jump.

**Comment by ihavenoface** [comment]
Ah, alright. This should be fixable.

**Comment by ihavenoface** [comment]
Build should be at https://ihavenoface.me.

**Comment by daisuke-asao** [comment]
Thank you, it works now!
