### ISSUE TITLE
Regarding new Index Navigation

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#263]
Is it possible to give us the option to choose whether or not we want to use the new Index Navigation?
For example, I personally prefer to use the in-built "all pages" from the native extension. and I probably got a million other reasons as well.
Possible?

**Comment by ihavenoface** [comment]
> For example, I personally prefer to use the in-built "all pages" from the native extension

What does it do different?

**Comment by ididntknowicoulddothatXD** [comment]
> What does it do different?

It loads all threads at the same time which breaks my browser.

It also breaks the native inline quick reply and report button on the index.

**Comment by ihavenoface** [comment]
Why would you want a broken native inline quick reply and report button on the index?

**Comment by ididntknowicoulddothatXD** [comment]
I've been using the original Firefox extension before it turned into native settings and I'm too used to it, especially to the report button.
I mainly use 4chan X these days to get features the native extension doesn't have.

**Comment by ihavenoface** [comment]
If you haven't even used 4chan x's quick reply then that's a no.
When building the index breaks your browser, you can use the Paged Mode.
