### ISSUE TITLE
Inline reporting?

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#265]
Well, sorry for bugging you with the native extension again, but would it be possible to add inline reporting?

**Comment by ihavenoface** [comment]
Test please.

**Comment by ididntknowicoulddothatXD** [comment]
Everything's working, thanks!

**Comment by ihavenoface** [comment]
![without_pass](https://f.cloud.github.com/assets/1175752/1505767/da10a758-48e7-11e3-85c0-d0b3deeb37e3.png)
![with_pass](https://f.cloud.github.com/assets/1175752/1505769/dcb004fe-48e7-11e3-8260-ea91d185972e.png)

Does this look good?

**Comment by ididntknowicoulddothatXD** [comment]
Yes, perfect. Maybe change the font of the Pass Message, if possible.

**Comment by ihavenoface** [comment]
What font do you want?

**Comment by ididntknowicoulddothatXD** [comment]
Bold Calibri, Verdana or Segoe UI, doesn't matter.

**Comment by ihavenoface** [comment]
I'll just enable Custom CSS on the page so you can change it as you like.

**Comment by ididntknowicoulddothatXD** [comment]
Sure thing, thanks.
