### ISSUE TITLE
Foolz Beta archives as of now

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#266]
Archives
/a/ Animu & Mango
/co/ Comics & Cartoons
/d/ Hentai/Alternative
/gd/ Graphic Design
/h/ Hentai
/jp/ Otaku Culture
/m/ Mecha
/mlp/ Pony
/q/ 4chan Discussion
/s4s/ Shit 4chan Shitposts
/sp/ Sports
/tg/ Traditional Games
/tv/ Television & Film
/u/ Yuri
/v/ Video Games
/vg/ Video Games - General
/vp/ Pokémon
/vr/ Retro Games
/wsg/ Worksafe GIFs

**Comment by ihavenoface** [comment]
A few have been remove because they can't be used by non-beta users.

**Comment by ihavenoface** [comment]
You can create your own archives.json and upload it somewhere, then link to it in the Archives tab in the settings.

**Comment by ididntknowicoulddothatXD** [comment]
Ok, thanks.

**Comment by ididntknowicoulddothatXD** [comment]
XMLHttpRequest cannot load http://a.pomf.se/e523u.json. Origin chrome-extension://4chanx is not allowed by Access-Control-Allow-Origin.

How do I fix this in Chrome? I googled and got to Stackoverflow but it's too confusing and I don't understand how to fix it.

**Comment by ihavenoface** [comment]
It means that pomf.se doesn't allow CORS. ~~Creating a gist should work.~~

**Comment by ihavenoface** [comment]
You can also try `http://jsonp.jit.su/?url=http://a.pomf.se/e523u.json`. It uses [JSONProxy](http://jsonp.jit.su/).

**Comment by ididntknowicoulddothatXD** [comment]
Yes, it worked, thanks!
