### ISSUE TITLE
Don't hook keybinds where they do nothing.

### ISSUE THREAD

**Issue by popman** [ihavenoface/4chan-x#270]
Certain keybinds do nothing in some cases, e.g. jump to next page and refresh index do nothing when viewing a thread.
In those cases it would probably work out better to ignore them, so they carry out their original function.

**Comment by ihavenoface** [comment]
The problem with Keybinds is that it is written to be hit or miss.
Rewriting every function to return the correct thing addressed in the keybinds is too recursive for the benefit this would give.
