### ISSUE TITLE
Page number missing in index mode

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#272]
Threads on index mode used to have a number indicating their current board page location. Since last night it's missing, the only thing I remember doing that could have caused it is accidentally installing the bleeding-edge version of the script, then browsing 4chan for some minutes, then reinstalling stable version. I tried with a new clean Firefox profile and the thread's page number is still missing.
Is there a way to bring it back?

**Comment by ihavenoface** [comment]
https://github.com/ihavenoface/4chan-x/commit/50a00052289afc8149425a729a69678205c419ed
https://github.com/ihavenoface/4chan-x/commit/06cb86506db1ac9db3d7181a749dc585c85a005b

I reverted the changes because the numbers aren't accurate and are just taking up space.
