### ISSUE TITLE
Fix 4chanX v2 branch for new markup changes

### ISSUE THREAD

**Issue by drtekrox** [ihavenoface/4chan-x#274]
Is this possible or is v2 branch officially dead now?

**Comment by ihavenoface** [comment]
What is wrong with the v3 branch?

**Comment by drtekrox** [comment]
It significantly changes the look and function of the page, 
Makes navigation harder by introducing extra clicks and a mandatory wait for the script to finish some ricey unfold animation, generally adds more bloat and increased cputime used for essentially the same functionality.

It'd be nice if v2 could stay around, it doesn't need any new features - just the occasional fix.

Anyhow, thanks for your time working on it the first place.

**Comment by ihavenoface** [comment]
I'll look what I can do.

**Comment by ihavenoface** [comment]
Tell me when something is missing.

**Comment by drtekrox** [comment]
Awesome, works well again mate.

Cheers again for all the effort, I do appreciate it.

**Comment by smcdude** [comment]
Thank you, noface!
