### ISSUE TITLE
Open Quick Reply text button at the top of the page

### ISSUE THREAD

**Issue by NoTimeForLove** [ihavenoface/4chan-x#275]
Why was this ever removed?

**Comment by ihavenoface** [comment]
1. It took up too much space.
2. We have the header with a button to click.
3. Keybinds are faster and more convenient. I recommend trying those out.

**Comment by NoTimeForLove** [comment]
> It took up too much space.

Add an option to turn it off?

> We have the header with a button to click.

I guess so but something about it just doesn't feel the same, the text button was easy, large, and convenient unlike that little button you need to precisely click 

> Keybinds are faster and more convenient. I recommend trying those out.

Sometimes I'm lazy and am just browsing with my right hand on the mouse and want to click open the QR box to post an image without moving my other hand to the keyboard to press buttons.

**Comment by ihavenoface** [comment]
> unlike that little button you need to precisely click 

Do this then:

```
.qr-shortcut:before {
  content: 'Quick Reply' !important;
  font-family: arial,helvetica,sans-serif;
  font-weight: 600;
}
```
