### ISSUE TITLE
.file-info isn't classed

### ISSUE THREAD

**Issue by Dotty** [ihavenoface/4chan-x#276]
Just an inconsistency with mainline X. The recent fix for ExLinks doesn't work without it.
Changing line 9234 to the following is an easy fix.

```
      return this.file.text.innerHTML = "<span class=file-info>" + (FileInfo.funk(FileInfo, this)) + "</span>";
```

Don't know how to do that with the sources though.

**Comment by ihavenoface** [comment]
https://github.com/ihavenoface/4chan-x/commit/ee2730016554ef6d0e6db8a2268450852b5c53bf
