### ISSUE TITLE
4chan X (2.39.1) filename and File Info Reformat errors

### ISSUE THREAD

**Issue by leveechan** [ihavenoface/4chan-x#277]
While I appreciate the recent update to 4chan X (2.39.1), which did cut back on the errors, I don't think 2.39.1 is fixed yet. Every so often I still get errors like the following wall of text. The errors occur randomly but most frequently when opening a thread on /a/ and when I do find an error-ed thread it stays error-ed everytime I refresh.
Also File Info Formatting does reformat the filename but only up to the ellipses(...) so when I mouse over it I don't even see the original entire filename, just 4chan's new 1386144996139 filename.
My Chrome is up to date and so is my Firefox with Greasemonkey 1.12

Here's the error as seen in Chrome, image attached because chrome wont let me ctrl+c
![untitled](https://f.cloud.github.com/assets/2664770/1716636/d8f93a84-61c3-11e3-8533-3ec0b8b35e94.png)
And here's the error as seen in Firefox
4chan X (2.39.1) error: filename is undefined
Report the bug at ihavenoface.github.com/4chan-x/#bug-report

URL: http://boards.4chan.org/a/res/98113960#p98114577
Build.shortFilename@file:///C:/Users/user/AppData/Roaming/Mozilla/Firefox/Profiles/ocdru392.default/gm_scripts/4chan_x/4chan_x.user.js:4560
FileInfo.node@file:///C:/Users/user/AppData/Roaming/Mozilla/Firefox/Profiles/ocdru392.default/gm_scripts/4chan_x/4chan_x.user.js:4272
Main.node@file:///C:/Users/username/AppData/Roaming/Mozilla/Firefox/Profiles/ocdru392.default/gm_scripts/4chan_x/4chan_x.user.js:7009
Main.featuresReady@file:///C:/Users/username/AppData/Roaming/Mozilla/Firefox/Profiles/ocdru392.default/gm_scripts/4chan_x/4chan_x.user.js:6929
.ready/cb@file:///C:/Users/user/AppData/Roaming/Mozilla/Firefox/Profiles/ocdru392.default/gm_scripts/4chan_x/4chan_x.user.js:359

Thank you for your time.

**Comment by ihavenoface** [comment]
Thanks for reporting.

**Comment by ihavenoface** [comment]
Please try that commit.

**Comment by leveechan** [comment]
Thanks a lot mate! I edited the 4chan_x.user.js in tampermonkey and greasemonkey and everything is smooth as a whistle.
