### ISSUE TITLE
While we're at it

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#283]
Please update the extension.

> 3.15.0 - 2013-12-13
> 
> More index navigation improvements:
> New setting: Anchor Hidden Threads, enabled by default. Hidden threads will be moved at the end of the index to fill the first pages.
> New setting: Refreshed Navigation, disabled by default. When enabled, navigating through pages will refresh the index.
> The last index refresh timer will now indicate the last time the index changed from 4chan's side, instead of the last time you refreshed the index.

**Comment by ihavenoface** [comment]
Will do when I find the time.

**Comment by ididntknowicoulddothatXD** [comment]
Thanks.
