### ISSUE TITLE
Load captcha when typing in the QR text box.

### ISSUE THREAD

**Issue by popman** [ihavenoface/4chan-x#284]
The captcha on 4chan doesn't load until you start to type a reply.

Trigger loading the captcha when a user types in the QR window to solve this.

**Comment by ihavenoface** [comment]
~~>the captcha doesn't load until you start typing a reply
load the captcha until you start typing a reply~~

Didn't even notice the change. Thanks for reporting.

**Comment by ihavenoface** [comment]
Done in 3ba0a058bf8debce8d42469e274f6825aef7c338.

**Comment by smcdude** [comment]
What about v2?
