### ISSUE TITLE
Post images from url

### ISSUE THREAD

**Issue by Spittie** [ihavenoface/4chan-x#292]
Hi, some anon [here](https://archive.rebeccablacktech.com/g/thread/40433233#p40437741) wanted me to send you a pull request for adding the "post images from url" icon like in my fork.

It's not a problem for me to send you a pull request, but are you interested in having it?
The biggest downside is that for working in Chrome, you need to add the "access data on every website" permission.

**Comment by ihavenoface** [comment]
Feel free to do so.

**Comment by Spittie** [comment]
Welp, it seems that I can't just fork your repo and send a pull request, as I already have a 4chan-x repository.

This is the .diff to apply: https://github.com/Spittie/test/commit/047bca59f05703e20b90c917dfe5f50ab1f0b681.diff

I've tested it, and everything seems to build/work just fine.
