### ISSUE TITLE
Quick Reply dialog creation crashed.

### ISSUE THREAD

**Issue by Jackonian** [ihavenoface/4chan-x#294]
"Quick Reply dialog creation crashed.
TypeError: $(...).textContent.trim(...).match(...) is null"

Every time I try and pop the quick reply open...

**Comment by ihavenoface** [comment]
Update to the latest version.

**Comment by Jackonian** [comment]
...ah. Looks like you released a new version just about right after I updated...

**Comment by ihavenoface** [comment]
It's buggy though. Hopefully I'll be able to fix this in the next few days.
