### ISSUE TITLE
"i" keybind always redirect to the board index

### ISSUE THREAD

**Issue by Poilaucul** [ihavenoface/4chan-x#296]
Hello,

I have the "i" key set to open Quick Reply since as long as I can remember and now it always redirects me to a board's index even though in my settings "i" key is set to open quick reply.
Is there a way to go around this?

BR.

**Comment by ihavenoface** [comment]
Can't reproduce. You can change Keybinds in the settings.

**Comment by Poilaucul** [comment]
I know and keybinds are set to "Open Quick Reply Without Quotes" with "i" in the settings.
Here is an export of my 4chan X's settings:
http://pastebin.com/N1c3XHW4
