### ISSUE TITLE
"Import failed due to an error."

### ISSUE THREAD

**Issue by iiiGerardoiii** [ihavenoface/4chan-x#298]
Can't import settings on v3.12.1 a window pops up saying "Import failed due to an error."

I'm using Chrome v33.0.1750.149 on OS X 10.9.2

![captura de pantalla 2014-03-12 05 35 07](https://f.cloud.github.com/assets/6264194/2396543/4012eefe-a9db-11e3-80b6-c92e02408c77.png)

**Comment by ihavenoface** [comment]
https://github.com/ihavenoface/4chan-x/blob/v3/CONTRIBUTING.md#reporting-bugs-and-suggestions
