### ISSUE TITLE
4chanX menus

### ISSUE THREAD

**Issue by Airdemon2100** [ihavenoface/4chan-x#300]
In both the catalog and the paged section, the 4chanX menu buttons do not work. If you click them, the menus do not appear, please fix this.

**Comment by ihavenoface** [comment]
https://github.com/ihavenoface/4chan-x/blob/v3/CONTRIBUTING.md#reporting-bugs-and-suggestions

**Comment by Airdemon2100** [comment]
Sorry, I am using Greasemonkey 1.15. I am using 4chanX 3.12.2, Firefox 28.

**Comment by ihavenoface** [comment]
Please update the extension.
