### ISSUE TITLE
Captcha will not go through 

### ISSUE THREAD

**Issue by linklonk** [ihavenoface/4chan-x#302]
Every time I try and post, the "You seem to have mistyped the CAPTCHA." message shows up. I tried like 50 times. but nothing. Disabling 4chan-x fixes it though

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT http://static.4chan-ads.org/ados.js
3
Uncaught TypeError: Cannot read property 'type' of null chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi/script.js:947
Uncaught TypeError: Cannot read property 'YT' of null 43048480:16557

**Comment by ihavenoface** [comment]
Try updating the extension.

**Comment by linklonk** [comment]
Still not working

**Comment by ihavenoface** [comment]
I can reproduce the error but I'm not yet sure what causes it.
