### ISSUE TITLE
query

### ISSUE THREAD

**Issue by Vafarien** [ihavenoface/4chan-x#303]
suggestion question
Will this fork work with OneeChan?
Does this fork have all the cool features seaweedsX had and spitties?

**Comment by Vafarien** [comment]
![fornofacetoanalyze](https://cloud.githubusercontent.com/assets/2349950/2598373/bfa5cfce-bac5-11e3-8569-ec4d2a68fa60.PNG)

This is my current interface

**Comment by ihavenoface** [comment]
> Will this fork work with OneeChan?

I don't use it so no idea.

> Does this fork have all the cool features seaweedsX had and spitties?

I don't know what cool features they have.

**Comment by Vafarien** [comment]
I will try to install your fork and see what happens when a third party X is combined with OneeChan.

**Comment by Vafarien** [comment]
The X setting are weird, can't set image cooldown to 30 instead it's locked at 60. And things are out of place since everything is centered, making the whole settings look out of place instead of being left alligned.

**Comment by ihavenoface** [comment]
This is a problem with OneeChan then.

**Comment by Vafarien** [comment]
![nofaceeoneechan](https://cloud.githubusercontent.com/assets/2349950/2598469/6455b5d2-bac8-11e3-9180-9c150f0231ed.PNG)
Yeah, or a combination of the two scripts having problems with eachother.

**Comment by ihavenoface** [comment]
OneeChan was built on top of 4chan X. If it's broken for my particular fork I can't and won't do anything about it. You might want to take this to the author of the extension.
