### ISSUE TITLE
[Feature request] Enable click to embed WebM files.

### ISSUE THREAD

**Issue by popman** [ihavenoface/4chan-x#304]
There's one thread on /g/ with them (for now) and it really sucks to have to open a new tab to view again.

**Comment by popman** [comment]
Adding an option to loop .webm files while they're embedded would be nice too.
Especially if you use a bit of css to change the player controls while embedding.

**Comment by ihavenoface** [comment]
https://github.com/ihavenoface/4chan-x/commit/fd2207cd36b7f95146dcd7d8db7d4e6f0eddb0cc
