### ISSUE TITLE
randomly hiding posts for no reason

### ISSUE THREAD

**Issue by NoTimeForLove** [ihavenoface/4chan-x#306]
I'm using stable on chrome 
http://i.imgur.com/fb3urNJ.png

**Comment by ihavenoface** [comment]
Can you check whether or not the filter hasn't caught anything by accident?

**Comment by NoTimeForLove** [comment]
/^(?!Anonymous$)/ wasn't commented out but this was on a fresh install of 4chan x... Did you accidentally do that in an update or was something screwed up with my install?

**Comment by ihavenoface** [comment]
I haven't done anything related to the filter so I suppose it was your setup/install. ~~Let me check again.~~

Looks fine on a vanilla installation.
