### ISSUE TITLE
Request: Renaming

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#31]
Know how there's Anonymize and the Filter and the Highlight feature of the filter?

I think it'd be cool to be able to change people's names and tripcodes with it since sometimes they get a bit excessive like Wizmoe's or jethro's (可愛がるGoldschlonger AKA DA OG based jethro AKA rip in piece WWPT !!4Q9SESccWeU)

From the user end it would just be like:

/jethro/r;name:both;new:'jethro'

r for rename, trip would have 'both' and 'only' for whether it wants to replace just the name or both the name and the tripcode, and new would obviously be to set the new name.

**Comment by zixaphir** [comment]
Doesn't the filter have the ability to add classes to filtered replies? Then you could just add, with the custom CSS built right into 4chan I might add, something like 

> .customclass .name, .customclass .tripcode { width: 0; overflow: hidden }
> .customclass .name::after { content: "Jethro"; }

**Comment by seaweedchan** [comment]
That's what the highlight feature does, but obviously there are more benefits to having a renaming feature, not to mention I hate using hacky CSS for something Javascript can do.

**Comment by zixaphir** [comment]
I'm just putting it out there that the functionality is more-or-less already there.

**Comment by seaweedchan** [comment]
Adding to this, part of it to hide the useremail part, as well, so maybe hide:all for name, tripcode, and email, hide:noemail, hide:name. All the functionality for this would already be in the highlight section and the Anonymize section, would just need some tweaking.

**Comment by ihavenoface** [comment]
Someone has requested to make the Anonymizer board specific which would fall under this issue. Just marking it here in case I forget about it.

**Comment by Croakier** [comment]
So um, any progress on this? I'm the guy who asked about making Anonymizer board specific by the way.

**Comment by ihavenoface** [comment]
No commits on a subject usually means no progress.
