### ISSUE TITLE
Constant Errors on inline quoted Embedding

### ISSUE THREAD

**Issue by ILsAllDoomed** [ihavenoface/4chan-x#310]
At random periods it will just crash. Sometimes it will work, other times it will shit out errors like nobody's business-

```
"Embedding" crashed on Clone No.######(/z/).
TypeError: el is null
"Embedding" crashed on Clone No.######(/z/).
TypeError: el is null
"Embedding" crashed on Clone No.######(/z/).
TypeError: el is null
"Embedding" crashed on Clone No.######(/z/).
TypeError: el is null
"Embedding" crashed on Clone No.######(/z/).
TypeError: el is null
"Embedding" crashed on Clone No.######(/z/).
TypeError: el is null
```

Also I've found that when it does work, it has two [Embed] tags- the first one doesn't work at all, but the second does.

Great feature but it's broken 60% of the time with inline quoting

**Comment by ihavenoface** [comment]
Do you have an example thread?

> two [Embed] tags

Can't reproduce. Please make sure you don't have any other addon / script active that might be interfering with 4chan X.

**Comment by ILsAllDoomed** [comment]
You were right. Whenever I have 4chan Media Player active it breaks it but only in some threads, like this one-
http://boards.4chan.org/a/res/105495049#p105500523
![capture](https://cloud.githubusercontent.com/assets/7276856/2688525/872e8a66-c2a7-11e3-845c-eb05dbfe48b7.PNG)
I'm using the latest version of it (5.0.5), should I repost this there?

Also, though you can see the [Embed] in the picture clicking on it doesn't work just to clear that up.

**Comment by ihavenoface** [comment]
You shouldn't run both anyway so I doubt they will care about this issue. You can disable Embedding in 4chan X if you would like to use 4chan Media Player.

**Comment by ILsAllDoomed** [comment]
> You shouldn't run both anyway.

Why? They do completely different things. They shouldn't even be interacting with a strawpoll since 4chan Media Player has nothing to do with that.

**Comment by ihavenoface** [comment]
> They do completely different things.

Both are suitable for embedding content.

**Comment by ILsAllDoomed** [comment]
Well it's supposed to only work with sound related links not strawpoll.
I apologize for bothering you with something that's not the fault of your script.
