### ISSUE TITLE
[Bottom] gone

### ISSUE THREAD

**Issue by hbno** [ihavenoface/4chan-x#313]
The [Return] [Catalog] [Bottom] bar is just gone.

**Comment by hbno** [comment]
A-are you dead? Plz answer me dead person
I think this was fixed in mayhem's version so all that's needed is a pull.

I don't know if you get this often, but I appreciate your fork more than any other even if sometimes I dislike the changes made, thank you for doing it.

**Comment by ihavenoface** [comment]
I'm fine, no worries.
