### ISSUE TITLE
Can't open Catalog Settings

### ISSUE THREAD

**Issue by iiiGerardoiii** [ihavenoface/4chan-x#314]
![adadfsdfas](https://cloud.githubusercontent.com/assets/6264194/2809668/e20b5bb0-cd7b-11e3-9a6f-b38e5728481c.gif) eh?

**Comment by ihavenoface** [comment]
This version of 4chan X is on 3.13.8. You might want to update it.

**Comment by iiiGerardoiii** [comment]
whoops wrong fork, my bad.
