### ISSUE TITLE
Youtube embeds not working

### ISSUE THREAD

**Issue by linklonk** [ihavenoface/4chan-x#319]
Sorry for bothering you so much

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT http://static.4chan-ads.org/ados.js
3
Uncaught TypeError: Cannot read property 'type' of null script.js:908
XMLHttpRequest cannot load http://dnsev.github.io/4cs/changelog.txt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://boards.4chan.org' is therefore not allowed access. 61451104:1
Uncaught TypeError: Cannot read property 'href' of null script.js:6948
2
Uncaught TypeError: Cannot read property 'href' of null

**Comment by linklonk** [comment]
Just tried with Liveleaks and Soundcloud too

**Comment by linklonk** [comment]
And vocaroo

**Comment by hbno** [comment]
Same for me, all embeds just broke for some reason.
No other scripts running, clicking embed does nothing.

**Comment by Shadowized** [comment]
floating embeds are broken, when I disable that setting it loads inline properly.

**Comment by ihavenoface** [comment]
Can reproduce. Thanks for reporting.
