### ISSUE TITLE
Single interval support

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#32]
How I have it set up now:

Active tab: 5,5,5,5,5,5
Background tab, 5,10,15,30,45,60

If I only use one 5 to show I don't want it to increase on active tab, it gives the "NaN" error after trying to increase it. Maybe you should duplicate the number automatically.

**Comment by ihavenoface** [comment]
87003404222658a256cae8e24306e5bf6fab7d60

**Comment by seaweedchan** [comment]
Actually sorry looks like the 5,5,5,5,5,5 gives the same error message. I forgot to update this.

**Comment by ihavenoface** [comment]
> looks like the 5,5,5,5,5,5 gives the same error message

It shouldn't.
I can't reproduce this on Firefox stable, Nightly and Chromium.

**Comment by seaweedchan** [comment]
At any rate what you put in seems to have fixed it.

**Comment by ihavenoface** [comment]
Oh of course. I thought it was throwing NaN regardless for you.
