### ISSUE TITLE
Inline reporting broken: Load denied by X-Frame-Options: Load denied by X-Frame... x does not permit framing

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#320]
Today inline reporting stopped working, the post report frame pops up but doesn't display any options.
I tried with latest Firefox with a clean profile and the console shows:

Load denied by X-Frame-Options: https://sys.4chan.org/t/imgboard.php?mode=report&no=123456789 does not permit framing

**Comment by ihavenoface** [comment]
> X-Frame-Options

Seems like 4chan is disallowing inlining the content then. Nothing I can do about other than reverting to the default popup.

**Comment by ihavenoface** [comment]
They resolved the issue.
