### ISSUE TITLE
Strawpoll embeds not working(?)

### ISSUE THREAD

**Issue by idhbn** [ihavenoface/4chan-x#327]
Youtube ones seem to work, but whenever I click on a strawpoll embed the little embed window shows up but with the actual strawpoll never inside it.

**Comment by ihavenoface** [comment]
Care to give an example thread?

**Comment by idhbn** [comment]
Just looked up one on /a/ - https://boards.4chan.org/a/thread/108351675

This is what shows up when clicking the embed for me
![capture](https://cloud.githubusercontent.com/assets/7571660/3182604/b0b57390-ec55-11e3-82b6-6d78450cd251.PNG)

Also how do I update the archive to include /v/'s new one?
The update option always shows "[object Object]" and "Last updated: Wednesday, December 31, 1969 4:00:00 PM".
![capture2](https://cloud.githubusercontent.com/assets/7571660/3182625/02fb73ca-ec56-11e3-8772-213df379a623.PNG)

Edit: The old icons and darker green are from a style script

**Comment by ihavenoface** [comment]
Try opening http://boards.4chan.org/a/thread/108351675.

**Comment by idhbn** [comment]
Same deal
![capture](https://cloud.githubusercontent.com/assets/7571660/3182730/31951fcc-ec58-11e3-8fac-24c213a7f160.PNG)

**Comment by ihavenoface** [comment]
![screen shot 2014-06-05 at 04 24 36](https://cloud.githubusercontent.com/assets/1175752/3182742/960567be-ec58-11e3-807b-02bed242b3e7.png)
Can't reproduce.

Please make sure that you're not having any privacy extensions blocking the request.

**Comment by idhbn** [comment]
This is weird as hell. I went and created a new profile for Firefox and it works there, but when I went back to disable all my addons in the one I'm currently using to see if it was a privacy extension doing it- it still won't work.
So I went and deleted 4chan X including its db files, reinstalled and it still refuses to work.
What could happen to this profile that would cause that?

**Comment by ihavenoface** [comment]
I don't know.
