### ISSUE TITLE
Hotfix to house-number captchas

### ISSUE THREAD

**Issue by popman** [ihavenoface/4chan-x#328]
If you fail a house-numeber captcha, you get a standard one.

Add an option to fail once in the background and continue from there.

**Comment by ihavenoface** [comment]
Failed captchas will increase the difficulty over time. That's why the QR now requires you to enter the submission field before grabbing a captcha.

**Comment by popman** [comment]
I know it increases difficulty, but the house captchas don't stop appearing until you fail one or more of them, and from my experience, they are completely impossible.
