### ISSUE TITLE
Refresh no longer working

### ISSUE THREAD

**Issue by Steelskin** [ihavenoface/4chan-x#333]
Using Chrome Dev x64 on Mac OS X
Refreshing the catalog yields the following error:
Index refresh failed. Error (0)
Command+R works though.

Same deal for thread, auto-refresh doesn't work, have to use Command+R

The issue seems to have something to do with permissions, that's the error message in the javascript console:
XMLHttpRequest cannot load http://a.4cdn.org/v/threads.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://gnhjbjalndahpllcacfkbjddcclhadpi' is therefore not allowed access.
Seems like a cross-site javascript permission error.

**Comment by ihavenoface** [comment]
https://github.com/MayhemYDG/4chan-x/issues/1699#issuecomment-48845715
