### ISSUE TITLE
ssl for 4chan-x.cf

### ISSUE THREAD

**Issue by bui** [ihavenoface/4chan-x#336]
because
![image](https://cloud.githubusercontent.com/assets/1788767/4165458/51081998-3502-11e4-8a1d-9a75de4091e5.png)

**Comment by ihavenoface** [comment]
I'm afraid this won't be possible unless self-signed.

**Comment by bui** [comment]
https://cert.startcom.org/

**Comment by ihavenoface** [comment]
![screen shot 2014-09-05 at 16 54 19](https://cloud.githubusercontent.com/assets/1175752/4166585/9228bdba-350c-11e4-92c3-fb79a05126f3.png)
