### ISSUE TITLE
"Unread" initialization crashed.

### ISSUE THREAD

**Issue by specialeddy** [ihavenoface/4chan-x#348]
Getting the following error upon loading or refreshing any thread on any board:

"Unread" initialization crashed.
[Exception... "<no message>" nsresult: "0x805e0006 (<unknown>)" location: "JS frame :: file:///C:/Users/Jordan/AppData/Roaming/Mozilla/Firefox/Profiles/vottcs2f.default/gm_scripts/4chan_X/4chan-X.user.js :: $.ajax</< :: line 333" data: no]

Firefox 33.1

**Comment by ccd0** [comment]
This is generally caused by another add-on (such as Adblock Plus or NoScript) blocking something.
https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions#why-was-4chan-x-blocked-from-loading-a-url

**Comment by specialeddy** [comment]
Thank you, I am no longer having the issue. While I have you ITT, could you please take a quick look at this other issue?

 https://github.com/ihavenoface/4chan-x/issues/338#issuecomment-60870257

This is not just me, and is a consistently reproducible error.

**Comment by ccd0** [comment]
> While I have you ITT, could you please take a quick look at this other issue?
> #338 (comment)

Well, it works in my fork.  It might be the problem that https://github.com/ccd0/4chan-x/commit/4ca58ff430593c5249b90a3294891aedbd5a7cca fixed, but I'm not sure.  But there have been several little changes to the captcha, and there will surely be more to come, so scripts will accumulate bugs if they aren't maintained.
