### ISSUE TITLE
Request: Menu entry for looking up poster/image in archive

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#35]

**Comment by ihavenoface** [comment]
Why not move the saucelist too?

**Comment by seaweedchan** [comment]
Because such a thing would clutter up the saucelist, its the type of thing that would benefit most from having a submenu in the menu for looking up by image, tripcode, name, etc.

**Comment by ihavenoface** [comment]
Sure.
I still need feedback on the change of the Updater. Breakage usually looks like when the post is already in the DOM but the Updater is still going instead of resetting to the usual cycle.

**Comment by seaweedchan** [comment]
Works so far. I'll report any issues I find.

**Comment by ihavenoface** [comment]
Thank you.

**Comment by ihavenoface** [comment]
Doing this it would probably look something like 0320721baa63069ff8bb2d1b48f58339e0673dea.
I have no idea what the archivers accept in terms of info though.

**Comment by seaweedchan** [comment]
For rebeccablacktech:
http://archive.rebeccablacktech.com/g/?task=search2&search_tripcode=!Ponyo.2wFe
http://archive.rebeccablacktech.com/g/?task=search2&search_username=seaweed
http://archive.rebeccablacktech.com/g/?task=search2&search_text=appchan
http://archive.rebeccablacktech.com/g/?task=search2&search_email=neko
http://archive.rebeccablacktech.com/g/?task=search2&search_subject=Desktop
http://archive.rebeccablacktech.com/g/image/kneRVpwy9ZglrxBhhxfeFg
http://archive.rebeccablacktech.com/g/?task=search2&search_filename=penis

For Foolz:
http://archive.foolz.us/a/search/username/example/
http://archive.foolz.us/a/search/tripcode/!MAdokaMiWg/
http://archive.foolz.us/a/search/subject/Naruto/
http://archive.foolz.us/a/search/email/neko/
http://archive.foolz.us/a/search/filename/penis/
http://archive.foolz.us/a/search/image/n3Ay7GYa072Lpy0kvA425A/

For InstallGentoo:
http://archive.installgentoo.net/diy?task=search2&search_username=Radiofag
http://archive.installgentoo.net/diy?task=search2&search_tripcode=!SW7uh6H3p.
http://archive.installgentoo.net/diy?task=search2&search_text=dog
http://archive.installgentoo.net/diy?task=search2&search_subject=hello
http://archive.installgentoo.net/diy/image/2JNxaOomgr_I3GKM-EIE4Q
http://archive.installgentoo.net/diy/?task=search2&ghost=&search_filename=penis
And no way to search by email.

**Comment by ihavenoface** [comment]
Thanks.

**Comment by seaweedchan** [comment]
No thank you for being the only 4chan X dev left that does anything lol

**Comment by ihavenoface** [comment]
We advance now

f41c9980fc3c234c7d9643940aa0c000bc23afaa

**Comment by seaweedchan** [comment]
Naisu!

It should hide the "name" and "subject" fields on Anonymous, tripcode-only name, or no subject.
Also still missing a search by image

**Comment by ihavenoface** [comment]
Yeah, it still needs some fine-tuning, especially the actual link construction. I will do that tomorrow.

> Also still missing a search by image

Already there with the entry 'Filename' when an image is in the post.

**Comment by seaweedchan** [comment]
Right now "Filename" does the same thing as "Post" (worked fine before the Post commit)

**Comment by ihavenoface** [comment]
Because I forgot to check whether it's the full post or not. With 2fafcd96ea900138b31642f9901d2e9ea88563f5 it doesn't sink through like that.

**Comment by seaweedchan** [comment]
Works~

**Comment by ihavenoface** [comment]
Also you are right - that's only the filename. Foolz was a bit picky about the format of the image hash/md5.

**Comment by seaweedchan** [comment]
Oh wellz.

**Comment by ihavenoface** [comment]
~~1eb77dcaa7a3bacfcc2df3980de0dc6510878c28~~
b236b273b97be871de9c929e573539b2371b9cd5

Major issues should be done by now except  ~~for heinessen being retarded and~~ for me having no idea what to do with the comments yet.
Please test.

**Comment by seaweedchan** [comment]
https://github.com/ihavenoface/4chan-x/pull/41
