### ISSUE TITLE
Request: hidden class/attribute on replyContainer when stubs hidden

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#36]
For userscripts that recolor even posts so that hidden posts can be ignored.

Right now the functionality is to just add [hidden] to .sideArrows

**Comment by ihavenoface** [comment]
Something like e5ff024379be6b96242578c6efe119385e64ce40?

**Comment by seaweedchan** [comment]
Doesnt seem to work

**Comment by ihavenoface** [comment]
Just to clarify, this

![madoka thread](http://ompldr.org/vZnYycA)

is what you want to reach? If so I wouldn't see where this is wrong.

**Comment by seaweedchan** [comment]
Hm, I did get it working a few times but its not consistent.

http://boards.4chan.org/g/res/28252072
Hid the top three replies in this thread, only one was given the class correctly.

<img src="http://i.imgur.com/nBacR.png">

**Comment by seaweedchan** [comment]
Also it does go away on refresh for those that do get the class.

**Comment by ihavenoface** [comment]
I only can reproduce the inconsistent behavior with stable firefox, although after reopening the inspector the class is added as it should be. Refresh doesn't affect the class at all.
Could you test this with a fresh profile?

**Comment by seaweedchan** [comment]
Behavior is the same on a fresh profile, however I noticed that it doesn't happen when stubs are enabled which in itself is good but not what I'm after.

**Comment by ihavenoface** [comment]
> when stubs hidden

Oh. Let me recap this for a second.

**Comment by ihavenoface** [comment]
e942c1974c47bdbe3afc5c30332d293cfc489544

**Comment by seaweedchan** [comment]
There we go :) Thank you!

**Comment by seaweedchan** [comment]
Actually one last request and please don't hate me:
Could you remove the .replyContainer class when the stub is hidden?

**Comment by ihavenoface** [comment]
Sure but why?

**Comment by seaweedchan** [comment]
Hm, actually I just tested it myself and OneeChan acts as if 4chan X isn't even there. Any advice?

**Comment by ihavenoface** [comment]
I don't follow? OneeChan seems to be working on my end.

**Comment by seaweedchan** [comment]
I mean for recoloring even posts.

:nth-of-type(even) when I remove .replyContainer still acts as if its there, and when I set it to specifically div[class$=replyContainer], acts if .hidden isn't there.

Oh well, I'll live without. Keep it how it is now because honestly that .hidden class seems much more clean anyway. Thank you for your help.

**Comment by ihavenoface** [comment]
One could also just insert `.even` and `.uneven` for the postContainer depending on its state, wouldn't that make life much easier than using some hacked-together hidden property?

**Comment by seaweedchan** [comment]
Everything would be much easier if I actually knew JS. :P
