### ISSUE TITLE
Blank Custom Navigation settings

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#37]
~~I can't even open the settings menu when I enable custom navigation, I have to go into about:config to redisable it.~~
Setting them to return default title names, empty namefields, email, w.e. if blank would be nice. 
~~**EDIT:** You cannot set Custom Navigation settings since you cannot even access them, enabling in the settings and switching to the rice tab just removes the "Custom Navigation is disabled" text and doesn't show the settings fields.~~
**EDIT:** Read [this comment.](https://github.com/ihavenoface/4chan-x/issues/37#issuecomment-9585041)

**Comment by ihavenoface** [comment]
https://github.com/ihavenoface/4chan-x/commit/a814dfd496836d683275bc2d14ad2707a2661b31#commitcomment-1992828

**Comment by vampiricwulf** [comment]
Oh, then let me fix the issue.

**Comment by ihavenoface** [comment]
I already dropped the idea of using CN for the namefields, the other branch/commit related to it was far from being anything at all yet.

> You cannot set Custom Navigation settings since you cannot even access them, enabling in the settings and switching to the rice tab just removes the "Custom Navigation is disabled" text and doesn't show the settings fields.

Works for me. Are you using the stable branch?

**Comment by vampiricwulf** [comment]
I just use master, I'll try again with stable branch when I can.

**Comment by vampiricwulf** [comment]
> > You cannot set Custom Navigation settings since you cannot even access them, enabling in the settings and switching to the rice tab just removes the "Custom Navigation is disabled" text and doesn't show the settings fields.
> 
> Works for me. Are you using the stable branch?

Found the issue, you can't immediately switch to the rice tab to adjust it, you have to close the floating window and reopen it without refreshing for the options to populate.

**Comment by ihavenoface** [comment]
I can't reproduce this at all.
