### ISSUE TITLE
Filter -> Comment menu option seems broken

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#44]
Browser: Aurora
## Pressing it results in error:

[19:36:11.760] TypeError: value.replace is not a function @ file:///C:/Users/seaweed/AppData/Roaming/Mozilla/Firefox/Profiles/ogw1km7i.Default%20Userasd/gm_scripts/4chan_x/4chan_x.user.js:957

**Comment by seaweedchan** [comment]
Also manually setting comment filters seems to not work.

**Comment by ihavenoface** [comment]
Can't say that I'm able to reproduce this.
I did make some changes on that type of filter and changed it back a little so you might be using something outdated - it now should look like this:

```
comment: function(post) {
  var content, data, i, nodes, text, _i, _ref;
  text = [];
  nodes = d.evaluate('.//br|.//text()', post.blockquote, null, 7, null);
  for (i = _i = 0, _ref = nodes.snapshotLength; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    text.push((data = nodes.snapshotItem(i).data) ? data : '\n');
  }
  if ((content = text.join('')).length !== 0) {
    return content;
  }
  return false;
},
```

**Comment by seaweedchan** [comment]
Yeah works fine in master, just not in stable.
