### ISSUE TITLE
Regarding the archive dropdown menu

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#48]
Please fix.
See:
https://github.com/MayhemYDG/4chan-x/issues/788

**Comment by seaweedchan** [comment]
Why would you need both if someone uses a tripcode anyway?

**Comment by ididntknowicoulddothatXD** [comment]
Never mind, I tried only Anon replies, when I found a tripfag I pressed the archive button and was redirected to the archive.
