### ISSUE TITLE
QR Keybind Fix-up (Idea)

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#49]
> As for the Fade part, that'd be best done by ihavenoface/mayhem adding a shortcut to toggle the autohide checkbox, which you should request on their repos.

Context: https://github.com/seaweedchan/OneeChan/issues/234

~~Should I ask this of @MayhemYDG instead?~~

**Comment by ihavenoface** [comment]
Suggest me a mac-friendly one.

**Comment by vampiricwulf** [comment]
Murder, I'm just going to close this issue for now, I'll reopen this when I finish doing a better job researching/using my brain.

**Comment by ihavenoface** [comment]
That was a joke.

**Comment by vampiricwulf** [comment]
You~ but still give me a bit to think this over, I feel like there's something vital that I should double-check before any action is committed.

**Comment by ihavenoface** [comment]
It's already done though.
32b1dc26147cdc6374c178b06ab54a481f690f12

**Comment by vampiricwulf** [comment]
Rage, I wasn't sure I said what I meant. Alice in Wonderland moment.

**Comment by ihavenoface** [comment]
Uhm okay.

**Comment by vampiricwulf** [comment]
Alright, that's a good addition, but now that I am home and no longer rushed, I can explain exactly what I mean.
I'd like it if when I open QR with a keybind, it would keep its toggle hidden setting instead of it auto turning it off.
To explain further: Pressing `Open QR`:
- Should keep auto-hide setting.
- Work the same as mouse-over (So that Oneechan's Slide Up and Fade work as if I moved my cursor over it.)

The keybind for Autohide would be unneeded if you do this.

Sorry for being autistic.

**Comment by ihavenoface** [comment]
I'll think about this tomorrow.

**Comment by vampiricwulf** [comment]
Take your time man, you don't even ahve to do anything if you don't want to, this IS your Repo.

**Comment by vampiricwulf** [comment]
I had a thought, instead of all that complicated stuff up there, if `Persistant QR` is enabled, the `Close QR` keybind should just hide it instead.
No need to bloat up everything.

**Comment by vampiricwulf** [comment]
Thank you.
