### ISSUE TITLE
  Adjust to new recaptcha (now a space must be provided). 

### ISSUE THREAD

**Issue by zunbar** [ihavenoface/4chan-x#5]
> (now a space must be provided).

Why? Make it as before, when we could simply enter enter the word.

**Comment by ihavenoface** [comment]
The new captcha requires the control and the scanned word to be written in the displayed order and it now must only provide exactly two words with a space in between.

**Comment by zunbar** [comment]
"true_word word2"

You type:

"true_word"

No spaces nothing.

4chan X transforms that in:

"true_word true_word"

Order doesn't matter anymore.

**Comment by ihavenoface** [comment]
This actually works. Thank you for the suggestion.
