### ISSUE TITLE
Request: Gallery mode for image expansion replacement

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#50]
Currently the image expansion feature feels like its kind of stuck in the past with the gallery mode that many websites seem to have nowadays so I think adding one to 4chan X would be great.

How it would work:

-Click image
-Image opens up centered on the screen set to auto fit (with padding to not overlap image info and links)
-Filename at the top
-At the bottom: number of current image / total number of images
-Previous image and next image links
-Clicking the image itself can either function as a second next button, or possibly toggle the auto fit to eliminate the need to open in new tab
-Clicking filename opens image in new tab
-Clicking anywhere else closes it
-Works with updater

Here's a mockup:

<img src="http://i.imgur.com/NB44M.png">

Side note: I'd also see if @MayhemYDG could help out but I'm banne

**Comment by ihavenoface** [comment]
I will look into this.

> and it would certainly bring some more attention to your fork.

It don't exactly care about attention for this fork. If people like it, I'm happy to provide something they like, if not I still have a script made to my liking. That's one of the reasons why I try to provide to the 'main' fork. Of course having people reporting bugs and providing new ideas is only a good thing.

**Comment by seaweedchan** [comment]
Well you could also post the idea to @MayhemYDG since he worked with you on improving the archiver links.

I would but he has me blocked with no explanation.

**Comment by ihavenoface** [comment]
I guess the answer will be something like 'This is a userscript, not a bulldozer~'.
However, I do like to write the stuff before proposing it anyway.

**Comment by seaweedchan** [comment]
Yeah he does seem to put a lot of priority into keeping 4chan X light and static (unless he comes up with the idea teehee), but I think a lot of us just want it to be something that can improve our 4chan experience as much as possible.

**Comment by vampiricwulf** [comment]
> I think a lot of us just want it to be something that can improve our 4chan experience as much as possible.

I know I do. Also I agree with seaweed, it would be a nice touch, it's one of my favourite features with Mimi and Chant.

**Comment by vampiricwulf** [comment]
Hey noface, I think you should move this enhancement up on your priority list, nearly everytime I browse I think about how nice this feature would be. I assume my thoughts aren't original and many others are thinking the same.

**Comment by ihavenoface** [comment]
> priority list

No such thing exists.

**Comment by vampiricwulf** [comment]
> No such thing exists.

Even if it isn't written, there's still one locked away in your cranium.

**Comment by ihavenoface** [comment]
Whatever. The problem is that this thing will be a completely new feature that will eventually exceed the usual 100 line-mark meaning new bugs, new stuff to look for, etc. while having other stuff like the current state of the linkifier that still requires improvements, or be it the redirect or whatever.
I'd much rather make things stable before beginning to write on new, broken stuff. Also I'll have to look where I'm leaving the aspect of performance of the script - I can't add features endlessly without expecting it to slow down.

**Comment by vampiricwulf** [comment]
I understand, bugs should always be number 1, I'm just saying that this enhancement would be more useful than a flag counter for /int/ or anything of those likes.
Found a script that could be referencial. Haven't tested/checked it yet.
http://userscripts.org/scripts/show/3791
Which is a fork of:
http://userscripts.org/scripts/show/2330
