### ISSUE TITLE
Costum navigation

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#51]
Why did you delete it...?

**Comment by ihavenoface** [comment]
cb47ba151c18924296c6b7f99773c90f6b431a1a

It was also terribly bloated. 160 lines to change a name of a few boards is just a bit too much. Might as well do it with plain old css.

**Comment by seaweedchan** [comment]
If people want it you can always point them to OneeChan, AppChan X, or 4chan SS.

**Comment by ididntknowicoulddothatXD** [comment]
Ok.
