### ISSUE TITLE
Add support for /f/'s tags

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#52]
So that you can actually post threads on /f/.

My original issue to Mayhem: https://github.com/MayhemYDG/4chan-x/issues/566

**Comment by vampiricwulf** [comment]
Seaweedchan brought up a simple replacement idea:

> Wouldn't be hard for 4chan X to change the <select> to /f/'s tag select since you wouldn't need the normal QR <select>.

In terms that I was able to understand, replace the "New Thread" form with the Tag form on /f/ as it is useless there.

**Comment by ihavenoface** [comment]
![blank](http://i.imagebanana.com/img/svvr2o2l/20121107112634_1920x1080_scrot.png)

It's indeed not hard to insert that node in the right place - the actual part is passing that information on post.
I've tried to find out what 4chan expects but have no idea under what keyword the select runs on.

**Comment by vampiricwulf** [comment]
Can you branch and give me that commit? I'll try to help where I can.

**Comment by ihavenoface** [comment]
18370ff5f1621b6fc5e5929ed05c785ff08a4a1b

**Comment by vampiricwulf** [comment]
Have you tried moving it into the form?
Currently it's under `<div class="move">` instead of `<form>` in the HTML.

**Comment by ihavenoface** [comment]
As is the original Thread Selector. Besides, it's not relevant from where I'm getting the value, it's only relevant how I'm going on submitting it on post.

To clarify →

```
QR.submit: (e) ->

// some cooldown stuff

post =
  // Harvest the values we need to submit to 4chan.
  // Doesn't matter from where that's coming, only where it's going.
```

**Comment by vampiricwulf** [comment]
@mootykins We can use some help here, plz respond ;_;

**Comment by vampiricwulf** [comment]
Is something in here: https://github.com/ihavenoface/4chan-x/blob/master/script.coffee#L2117 \* that we're overlooking?

**Comment by ihavenoface** [comment]
wat

**Comment by vampiricwulf** [comment]
I'm saying maybe there's a node that's not being pushed.

**Comment by ihavenoface** [comment]
The node is the part that sets what's visible in the DOM and for the user. We want to send user input.

**Comment by ihavenoface** [comment]
`Content-Disposition: form-data; name="filetag"`

Well yeah.

**Comment by vampiricwulf** [comment]
https://github.com/ihavenoface/4chan-x/commit/18370ff5f1621b6fc5e5929ed05c785ff08a4a1b#L1R2130
Why is that disabled?

**Comment by ihavenoface** [comment]
Because I was searching for the correct value, read "We want to send user input.". ~~Turns out that 4chan will search it itself.~~ The request is "filetag", not "tag" though.

Next thing is that I have to do is adding the correct error handling - 4chan x isn't aware of tags yet.

**Comment by ihavenoface** [comment]
524f163939dbbe2a30c65cf6e5292efa3a9aafaa

Now we are talking. I'll do the rest tomorrow.

**Comment by vampiricwulf** [comment]
![](http://puu.sh/1nLNj)
Feels good to almost being able to post again on /f/ after all these months. Thank you for doing this.

**Comment by ihavenoface** [comment]
~~bfa1941a04e60e1da8d9ebadeeb8b4612ce1e2a4~~ d9ba30b45f5261215c3dcad966ac44ecb1ff1719

Please test, etc.
Also please try to purposely write captchas wrong or post duplicate files not only on /f/ but also on other boards. I need to make sure not to screw up the error handling all together.

**Comment by vampiricwulf** [comment]
Duplicate:
f:
![](http://puu.sh/1nRr6)
a:
![](http://puu.sh/1nRut)
Captcha: (Fuck there's like 4 Pass cookies)
f:
![](http://puu.sh/1nRzu)
a:
![](http://puu.sh/1nRyA)

Need more?

**Comment by ihavenoface** [comment]
Looks good.
Normal posting works on both boardpage and thread?

**Comment by vampiricwulf** [comment]
Yep.
