### ISSUE TITLE
Firefox crashes every time I reply to a thread

### ISSUE THREAD

**Issue by MaddoScientisto** [ihavenoface/4chan-x#54]
Firefox nightly to be precise, it crashes
EVERY
SINGLE
TIME
I reply to a thread.
If I don't have a picture then the post still goes through, if there is a picture it doesn't

EDIT: I switched to mayhem's and it still happens, going to try to post without any scripts

Confirming that without any scripts it doesn't crash

**Comment by ihavenoface** [comment]
Firefox Nightly is profound to crashing. There's not much I can do about it.
Does the stable / aurora branch crash for you? Have you tried a new profile?

**Comment by Toora** [comment]
This is caused by the Quick Reply. I would suggest disabling it and turning on the inline extension and use the QR there until Nightly is fixed. Just test each new build.

**Comment by MegaMoses** [comment]
Getting the same issue.  Also crashes whenever I select an image to upload.
Only in Nightly.  Tested it with a clean install with nothing but Greasemonkey and both versions 4chan X with the same problem.  Stable and Aurora are fine.

**Comment by ihavenoface** [comment]
> Stable and Aurora are fine.

Then use that until ~~https://bugzilla.mozilla.org/show_bug.cgi?id=810588~~ the other one is fixed.

**Comment by vampiricwulf** [comment]
It's actually this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=810520 (Which was fixed last night)

**Comment by ihavenoface** [comment]
It said crash and js so and I wasn't bothered enough to search any further.

**Comment by vampiricwulf** [comment]
Good enough reason for me too, but I decided to check it in `about:crashes`
