### ISSUE TITLE
Linkify causing occasional error upon opening threads in Chrome

### ISSUE THREAD

**Issue by obrien-d** [ihavenoface/4chan-x#55]
The threads that throw the error seem completely random. When the "linkify" option is disabled, the thread loads normally.

4chan X (2.36.3) error: Cannot read property 'textContent' of nullReport the bug at ihavenoface.github.com/4chan-x/#bug-reportURL: https://boards.4chan.org/a/res/74520112TypeError: Cannot read property 'textContent' of null    at Object.Linkify.text (eval at <anonymous> (eval at eventHandler (eval at <anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/content.js:56:21))), <anonymous>:5603:49)    at Linkify.node (eval at <anonymous> (eval at eventHandler (eval at <anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/content.js:56:21))), <anonymous>:5573:31)    at Object.Main.node (eval at <anonymous> (eval at eventHandler (eval at <anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/content.js:56:21))), <anonymous>:6053:13)    at Main.ready (eval at <anonymous> (eval at eventHandler (eval at <anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/content.js:56:21))), <anonymous>:5980:12)    at HTMLDocument.cb (eval at <anonymous> (eval at eventHandler (eval at <anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/content.js:56:21))), <anonymous>:374:16)

**Comment by ihavenoface** [comment]
#24
I'm not yet quite sure what the solution will be but until this is fixed you can use the master branch located at https://github.com/ihavenoface/4chan-x/raw/master/4chan_x.user.js.
