### ISSUE TITLE
Prefetch images.

### ISSUE THREAD

**Issue by emoloney** [ihavenoface/4chan-x#57]
Please prefetch all images and display thumbnails as downscaled originals like you do with pngs and gifs. It would look better for those of us that browse the site with an increased zoom level in our browsers.

Thank you.

**Comment by ihavenoface** [comment]
![](http://i.imagebanana.com/img/nufg9c1i/scrot.png)

**Comment by emoloney** [comment]
Cool, high quality thumbnails await me!

...

I can't find this button when I'm not in reply mode, and I don't want to click it manually.

**Comment by ihavenoface** [comment]
> I can't find this button when I'm not in reply mode

It can't be helped.

> and I don't want to click it manually.

Guess why we have the button?

**Comment by emoloney** [comment]
I wish it was like the PNG thumbnail fix where it's all automatic.

**Comment by ihavenoface** [comment]
Well I won't be the one granting you this wish, I'm sorry.
