### ISSUE TITLE
Randumb Idea (Github Inspired)

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#58]
Feel free to say no.

Post Preview.

**Comment by ihavenoface** [comment]
I don't follow?

**Comment by seaweedchan** [comment]
<img src="http://i.imgur.com/mp9wf.jpg">

**Comment by ihavenoface** [comment]
It's also silly since I have no way of determining how 4chan will parse my post. Well I do but that will be too much work for nothing.

**Comment by vampiricwulf** [comment]
Alright, I was just wondering because I have no idea what boards have spoilers enabled and shit like that.

**Comment by ihavenoface** [comment]
I don't have either but restricting them like I did in fa9e8b3b98c20e7c82388ea334ebdac1c12482ed (simply not adding them when doing the keybind) is probably a better idea.

**Comment by vampiricwulf** [comment]
Yeah, but what I was hoping was one that's universal for all even if you type in the tag and such, but as you say, it's too much work if it's possible.

**Comment by seaweedchan** [comment]
> I have no idea what boards have spoilers enabled and shit like that.

what

Just look for the "spoiler" checkbox, not that hard.

**Comment by vampiricwulf** [comment]
Oh? Those correspond? Never thought to test that.

**Comment by ihavenoface** [comment]
@seaweedchan 
~~textarea spoiler != image spoiler~~

The more you know.

**Comment by ihavenoface** [comment]
Here goes. 859224b7c96c9c1c5fabef416ba7b2db153181c0
