### ISSUE TITLE
Latley I keep getting this error.

### ISSUE THREAD

**Issue by alex68785** [ihavenoface/4chan-x#6]
2.34.5
http://boards.4chan.org/a/
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0

([object Object])@chrome://scriptish/content/scriptish.js -> file:///C:/Users/Jon/AppData/Roaming/Mozilla/Firefox/Profiles/febeprof.test/scriptish_scripts/4chanx@aeosynth/4chanx@aeosynth.user.js:3582
([object Array],true)@chrome://scriptish/content/scriptish.js -> file:///C:/Users/Jon/AppData/Roaming/Mozilla/Firefox/Profiles/febeprof.test/scriptish_scripts/4chanx@aeosynth/4chanx@aeosynth.user.js:5565
()@chrome://scriptish/content/scriptish.js -> file:///C:/Users/Jon/AppData/Roaming/Mozilla/Firefox/Profiles/febeprof.test/scriptish_scripts/4chanx@aeosynth/4chanx@aeosynth.user.js:5459
([object Event])@chrome://scriptish/content/scriptish.js -> file:///C:/Users/Jon/AppData/Roaming/Mozilla/Firefox/Profiles/febeprof.test/scriptish_scripts/4chanx@aeosynth/4chanx@aeosynth.user.js:322

It said to submit it here.

**Comment by ihavenoface** [comment]
You are running an outdated version of both Firefox and 4chan x.
Please update them and report back if this error still occurs.

**Comment by zixaphir** [comment]
scriptish is deaaaaaaad

**Comment by alex68785** [comment]
Scriptish died? and I prefer to keep my current version of firefox. I just updated 4chan x. Oddly the error pops up but it operates as normal. I only posted because the error popup says to.

**Comment by ihavenoface** [comment]
The development Scriptish has been dead for 3 months and Greasemonkey has become quite usable again.

> and I prefer to keep my current version of firefox.

Why is that?

Could you post the new error? It's probably because I've merged some commits dedicated to Firefox 15 and 17.
