### ISSUE TITLE
Coloured User IDs?

### ISSUE THREAD

**Issue by Poilaucul** [ihavenoface/4chan-x#61]
Color User IDs have been introduced in the inline extension recently, the problem is it doesn't work well along with 4chan X auto post fetcher, fetched replies user IDs do not have colors.
Could colored User IDs be added natively to 4chan X?

**Comment by vampiricwulf** [comment]
#56

**Comment by ihavenoface** [comment]
22325ed55fee14e39c490a8b0ba5c7f6fc31db2b
