### ISSUE TITLE
Sage cooldown broken

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#62]
Using the latest stable and the latest master

Counts down from 60 to 29, and then when it reaches 0 again it goes to 29 again. Should obviously be going from 60 to 59.

Using Aurora.

**Comment by ihavenoface** [comment]
This got baked in with a72a88ce5fde960b1098437461ae75a2fddac14e - it's the same on Mayhems fork.
No idea if I'm going to find the issue.

Thanks for reporting.

**Comment by ihavenoface** [comment]
> You can submit a non-sage post 30 seconds after a sage one.

Oh. This is new.

**Comment by seaweedchan** [comment]
Strange.

Maybe put the second cooldown in parentheses as an indicator.

Like regular cooldown:
30
then which it reaches 0
(30)

**Comment by seaweedchan** [comment]
And oddly enough right now it just counted down from 60 normally.

**Comment by ihavenoface** [comment]
Should be fixed in v3.
