### ISSUE TITLE
Ctrl+S to spoiler now just tries to save the page

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#63]

**Comment by ihavenoface** [comment]
859224b7c96c9c1c5fabef416ba7b2db153181c0

**Comment by seaweedchan** [comment]
But I'm doing it where it IS possible. This was true with both /a/ and /vg/.

**Comment by ihavenoface** [comment]
I can't reproduce this in both firefox and chromium, sorry.

**Comment by Teapsalm** [comment]
Yep, having this on both Pale Moon and Firefox Nightly.

**Comment by ihavenoface** [comment]
Are you using OneeChan by any chance?

**Comment by seaweedchan** [comment]
Works, thanks~

Also yeah whoops looks like it did just happen with OneeChan.
