### ISSUE TITLE
Fix thread watcher, maybe?

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#64]
> New inline extension features: improved thread watcher (threads with new posts will be bold, and will also show you unread count
> MOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOT!

**Comment by ihavenoface** [comment]
I'm not sure what you are trying to tell me with this.

**Comment by ihavenoface** [comment]
Is this a race or something?

**Comment by ididntknowicoulddothatXD** [comment]
Yes.

**Comment by ihavenoface** [comment]
Wrong answer.

**Comment by ididntknowicoulddothatXD** [comment]
R.I.P.

**Comment by ihavenoface** [comment]
You are free to rescue it.

**Comment by ihavenoface** [comment]
Not very.
Well actually I would have to find out how to deal with requests outside of the current webpage.

**Comment by ihavenoface** [comment]
Looks like some people actually have a use for this and since ajax isn't a problem anymore I did reconsider this issue.

**Comment by vampiricwulf** [comment]
Yay, I was actually kinda looking forward to this, thread watcher is kinda shit without this. I use it only to keep old threads I like marked to read later in the archive.

**Comment by Poilaucul** [comment]
My thread watcher randomly misses threads.
I don't think it is tied to which board you are browsing, right? The list stays the same on every board?

**Comment by ihavenoface** [comment]
Are you using Chrom*?

**Comment by Poilaucul** [comment]
Up to date Firefox and 4chan X

**Comment by ihavenoface** [comment]
Chrom based browser are known to throw out the local storage when clearing cookies so that would have been my first guess. Other than that I have no idea since I don't use the watcher, sorry.

**Comment by Poilaucul** [comment]
Not all watched threads disappear through.

**Comment by ihavenoface** [comment]
Queued in main fork.
