### ISSUE TITLE
Can't filter posts with no comment.

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#68]
Hi.
I'm trying to filter all posts with no comment, even if they have images attached. I tried the usual regexp:

/^$/

but it doesn't work. I created a new firefox profile with only Scriptish and 4chan X installed to see if other extensions or scripts interfere with the script and prevent this particular filter to come into effect. The regexp still doesn't work with this fork, but it does with the Mayhem version.
Can this be fixed?

**Comment by ihavenoface** [comment]
Oh right, thanks for reminding me.
