### ISSUE TITLE
Stuck posting

### ISSUE THREAD

**Issue by MaddoScientisto** [ihavenoface/4chan-x#7]
Since a few hours ago I'm not able to post anymore, the posting window appears like this: http://www.jackomel.com/images/screens/2095.png

no matter if the captcha is right or not it stays like that, even if I have a bunch of stored captcha pressing the buttom consumes them one by one

**Comment by ihavenoface** [comment]
I cannot reproduce this.
Any output in the console (Ctrl + Shift + J)? What browser and version of 4chan x are you using?

**Comment by MaddoScientisto** [comment]
Firefoz nightly and grease monkey,  I'll report on the output later

**Comment by MaddoScientisto** [comment]
Timestamp: 28/08/2012 02:53:18 PM
Error: TypeError: text is null
Source File: file:///F:/Users/Jack/AppData/Roaming/Mozilla/Firefox/Profiles/pacrnjz1.default/gm_scripts/4chan_x/4chan_x.user.js
Line: 659

**Comment by ihavenoface** [comment]
Markdown seems to be the cause. Currently, if it is enabled, you will have to put at least one character (can be a space) when posting with only an image.

**Comment by MaddoScientisto** [comment]
disabling it indeed fixed the issue
