### ISSUE TITLE
Admin Replies in OP

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#70]
They don't update when new admin replies come, they use to, is it just me?
By update I mean it doesn't tack on quote links to the posts that have appeared since I opened the page.

**Comment by ihavenoface** [comment]
There's probably no good way to test for this without changing Get.

**Comment by vampiricwulf** [comment]
You have some time to test:
http://boards.4chan.org/q/res/304379 Moot in action and frequent.

**Comment by ihavenoface** [comment]
I'm on a mobile connection right now.

**Comment by vampiricwulf** [comment]
Oh, I see, then  if you don't feel like it's necessary, just close the thread.
And remember: I'm willing to help anyway you tell me to~

**Comment by ihavenoface** [comment]
Over at https://github.com/ihavenoface/4chan-x/commits/soundcloud I'm trying to get soundcloud embedding working (the pretty way, not simply generating the iframe yourself) - you're welcome to find my error so I can end this.

**Comment by vampiricwulf** [comment]
I'll give it a test later, just stressing out now, got a phone call I'd rather not have.

**Comment by ihavenoface** [comment]
Nevermind - works now.
