### ISSUE TITLE
Youtube Embed HTTPS Error

### ISSUE THREAD

**Issue by ldgbc** [ihavenoface/4chan-x#73]
The latest version seem to force Youtube embed to have HTTPS (I think it force ytimg.com) whether it the link is HTTP/S or not. 

This cause a "An Error Has Occurred" when trying to play.

No point from the previous version (2.36.8)

**Comment by ihavenoface** [comment]
Are you using Firefox Nightly by any chance? 
Could you link me to the post where you're trying to play the video in?

**Comment by ihavenoface** [comment]
Feel free to comment here should this occur again. Closing for now.
