### ISSUE TITLE
Youtube embed doesn't work with extended replies

### ISSUE THREAD

**Issue by HarHar** [ihavenoface/4chan-x#74]
Like, if you use the "(embed)" link on a post that was followed from a link of another post, it won't work

**Comment by HarHar** [comment]
And if there's a video playing and you click a reply backlink of that post, it will stop

**Comment by ihavenoface** [comment]
Thanks for reporting.

**Comment by Poilaucul** [comment]
Neither do Vacaroo links.

**Comment by ihavenoface** [comment]
Yeah because we are slapping embeds on the site in the same manner so any service can be considered equally broken.

**Comment by zixaphir** [comment]
This should be fixed with the 

```
    if post.isInlined and not post.isCrosspost
      if Conf['Embedding']
        for embed in $$('.embed', post.el)
          $.on embed, 'click', Linkify.toggle
      return
```

that appchan x uses.

**Comment by ihavenoface** [comment]
> `post.el`

Besides - I wish I was able to display the embedded document in hover and inline.

**Comment by zixaphir** [comment]
> `post.el`

What about it?

> Besides - I wish I was able to display the embedded document in hover and inline.

That doesn't sound so hard. I mean, we already have iHover. We can move it into its own global method and call it from embedding and image hover.

**Comment by zixaphir** [comment]
> We can move it into its own global method and call it from embedding and image hover.

Actually, double-thinking it, we could just move it into the UI section.

**Comment by zixaphir** [comment]
Even further actually looking at the code after opening my mouth, most of the code already is in UI.

**Comment by ihavenoface** [comment]
> What about it?

I'm using only blockquote later on.

> most of the code already is in UI.

It's still work.

**Comment by zixaphir** [comment]
I'm not feature requesting, I'm implementation brainstorming.

> I'm using only blockquote later on.

Smart.

On a sidenote, I've been doing a lot of random benchmarking of code and trying to figure out ways we can increase performance.

It really bothers me that performance really starts to fall off after 300 posts.

**Comment by ihavenoface** [comment]
> I'm not feature requesting

I know.

> It really bothers me that performance really starts to fall off after 300 posts.

Doesn't happen in 4chan X™.

**Comment by zixaphir** [comment]
> Doesn't happen in 4chan X™.

You sound like Mayhem.

**Comment by ihavenoface** [comment]
![1351450803895](https://f.cloud.github.com/assets/1175752/15737/2d54e512-47bf-11e2-94e8-a451d74213f1.jpg)
No.
