### ISSUE TITLE
4chan X makes new catalog ugly

### ISSUE THREAD

**Issue by seaweedchan** [ihavenoface/4chan-x#75]
See: http://boards.4chan.org/g/catalog

**Comment by seaweedchan** [comment]
Also, .current isn't applied to links on the catalog.

**Comment by ihavenoface** [comment]
Thank you.
I'm able to identify a catalog `{BOARD: "g", CATALOG: true}` but am not entirely sure what is making it look so fancy.

**Comment by ihavenoface** [comment]
Looks like the main css is the cause which leaves me with two options - completely disable 4chan x on a catalog or write an external css to style the settings menu of 4chan x. I'm tending to go with the former.

**Comment by seaweedchan** [comment]
4chan X styles #content for its options, and #content is used on the catalog instead of #delform.

What point is there though to having 4chan X loaded on the catalog anyway? I can't think of anything its worth having there for.

**Comment by seaweedchan** [comment]
> I'm tending to go with the former.

I probably would, too.

**Comment by ihavenoface** [comment]
Alrighty.
