### ISSUE TITLE
Some suggestions and a css problem

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#76]
Hi.
I noticed that new fetched posts that are filtered are ignored by the unread count on the tab title. Is it possible to add a setting on the filters so one can specify if new filtered/highlighted posts are counted or ignored on the unread count?

Is it possible to allow quotelink formatting in the rice section for links to OP's and cross-thread links? I'd like to use a → to indicate cross-thread links, like the inline 4chan extension, I edit the script to do it but the change is overwritten every time I update 4chan X.

The highlight ID feature on /b/ from the 4chan inline extension doesen't work with new posts fetched by 4chan X, is there a way to solve this?

One last thing, sorry if this doesn't go here, I'm learning CSS and I have trouble trying to do something and wondered if I can get help here. This could be easely solved if the first suggestion above was implemented. Instead of completely hiding filtered posts (with or without putting a stub toggle on top of them), I'd like to leave the .reply visible with only the blockquote tag and .file class hidden so long as the .reply isn't hovered with the mouse. To do this I created a userstyle with the following:

.hidden .reply
{display:block!important}

.hidden .reply:not(:hover) .file,
.hidden .reply:not(:hover) blockquote
{display:none!important}

This is close to what I want to do, the problem is that setting the .reply to display:block makes the reply take the whole window width. Setting it to display:inline messes all the replies up. Is there a way to display new fetched filtered posts with their proper, "unfiltered" width using only CSS while remaining ignored on the unread count?

Here's an example: http://postimage.org/image/fjovfcejh/

That's all. Thanks for your time.

**Comment by ihavenoface** [comment]
Sure.

Sure.

That's already implemented, see https://github.com/ihavenoface/4chan-x/issues/56#issuecomment-10634375. ID colors have to be active.

I'll read the last part again when I'm not tired just to assure I got that right.
