### ISSUE TITLE
Why is linkify not working (Extension broken)

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ihavenoface/4chan-x#77]
http://puu.sh/1xdbg

Using latest version, official disabled and Chrome

**Comment by ihavenoface** [comment]
Could you link me to the thread?

**Comment by ihavenoface** [comment]
Nevermind I found https://boards.4chan.org/a/res/75847117 and https://boards.4chan.org/g/res/29603068 but both work for me just fine.

Try opening the console and paste the output here.

**Comment by ididntknowicoulddothatXD** [comment]
Found the problem.

Can you please check if 

> Resurrect Quotes: Linkify dead quotes to archives

and the linkification option are in conflict with each other if you disable one?

In my case, I disabled ``Resurrect Quotes'' and left the Linkification options on. It would be nice to fix it, I don't really want to resurrect Quotes at all.

**Comment by ihavenoface** [comment]
Yep that was it. Thank you.
