### ISSUE TITLE
Catalog - when you get to it

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#78]
- Image Auto-Gif
- Png Thumbnail Fix
- Reveal Spoilers

Ones mentioned below:
- Image Hover

**Comment by ihavenoface** [comment]
> Reveal Spoilers

![](http://i.imagebanana.com/img/vnb73zbt/123.png)

**Comment by seaweedchan** [comment]
Image hover as well.

**Comment by vampiricwulf** [comment]
Oh, Oneechan hides the original settings.

**Comment by ihavenoface** [comment]
> Image hover as well.

This will collide with the integrated text hover.

> OneeChan in charge of not being silly

**Comment by ihavenoface** [comment]
Also  @seaweedchan could you write `v2.37.0 or newer of ihavenoface X` instead of `v2.37.0 of ihavenoface X`?

**Comment by ihavenoface** [comment]
The catalog doesn't actually reveal the filetypes of the thumbs.
It would be possible to somehow get them with catalog.json but that's not what the catalog is meant for imo.
