### ISSUE TITLE
"Show page number for thread you're in"

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#79]
https://github.com/MayhemYDG/4chan-x/issues/571
https://github.com/MayhemYDG/4chan-x/issues/832
It's considered bloat by Mayhem's standards, it's pretty useless imho, but it looks like some people want it.

**Comment by ihavenoface** [comment]
#56 - point five

**Comment by vampiricwulf** [comment]
Oh durr, I haven't looked at the OP of that issue in a while so I forgot about it.

**Comment by ihavenoface** [comment]
He asked for that from when he created the issue though?

**Comment by vampiricwulf** [comment]
Yeah, but my mind blanked on it.
