### ISSUE TITLE
Error popup demands too much attention

### ISSUE THREAD

**Issue by MaddoScientisto** [ihavenoface/4chan-x#8]
Let's say I'm dumping a bunch of pictures and have a bunch of captchas cached and then while it's dumping I go to do other stuff in other tabs.

OH! What's this? Invalid captcha! Fuck what you were doing get your ass in this tab and stare at the error!

What I am saying is, when there's an error to display switching to the tab every time is REALLY annoying, expecially if I'm dumping something that I don't really want other people to see and BAM, it's suddenly there for everyone to see.

My suggestions are either not making it autoswitch to the tab or popping up a regular popup (unless doing that still switches the tab of course)

**Comment by ihavenoface** [comment]
How about 0a98136bb508402107f6c0ddc6551b2c86e1f99e?

**Comment by MaddoScientisto** [comment]
it's perfect

**Comment by ihavenoface** [comment]
Good.
