### ISSUE TITLE
Frames support for catalog link toggling

### ISSUE THREAD

**Issue by snaptop** [ihavenoface/4chan-x#81]
So something like this

![frames](http://i.imgur.com/x8RMu.png)

**Comment by ihavenoface** [comment]
Oh wow I completely misread this issue but now we can insert 4chans frames to the catalog with a41a91dca6990ad84011efbc560ae390e968e221.

On a different note - I don't seem able to communicate with the frame tree, `window.top | window.parent` returns undefined. Do you know what's up with that?
Maybe adding the frame to body isn't bad after all.

**Comment by ihavenoface** [comment]
Since this doesn't seem active or actually wanted I'll close this for now.
