### ISSUE TITLE
replace thumbnails of loaded pictures with scaled versions of the full picture

### ISSUE THREAD

**Issue by fullmetal1** [ihavenoface/4chan-x#82]
Now that furryfox is getting decent image scaling I think this should be implemented.

**Comment by seaweedchan** [comment]
Image prefetching does this, because that WOULD have to preload all images.

**Comment by ihavenoface** [comment]
b2aa72dd5120f0a63af3a80c86b9367a1809a626 does this. Not yet for posts from the updater but I'll do that once I've rewritten/joined the various types of image preloading into one function.

**Comment by fullmetal1** [comment]
@seaweedchan I'm not saying to load all images and then change the thumbnail. I'm saying to check the images that have been loaded (from hovering, expanding, prefetching, or png/gif thumbnail replacement) and replace them all as they are loaded with scaled version of their full images. You don;t need to preload all images to replace the loaded ones with the full size images.

@cockdicks that's just preloading all images and fixing the thumbnails afterwords. The difference between that and my suggestion is that this one should only replace the thumbnails of images that have already been loaded.

**Comment by ihavenoface** [comment]
Oh of course.
