### ISSUE TITLE
Refresh button is gone

### ISSUE THREAD

**Issue by emoloney** [ihavenoface/4chan-x#85]
Main | Filter | Sauce | Rice | Keybinds | 
used to be
Main | Filter | Sauce | Rice | Keybinds | Refresh

but "Refresh" is now gone. It looks like a bug to me since the pipe is still there.

**Comment by ihavenoface** [comment]
Can't say it's gone for me. Try checking https://github.com/ihavenoface/4chan-x/blob/master/4chan_x.user.js#L2941 in the file where your script is saved.
![](http://i.imagebanana.com/img/a7vhei2h/scrot.png)

**Comment by emoloney** [comment]
Whoops, it was my adblock. Thanks for replying.
