### ISSUE TITLE
Prefetch - Question.

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#86]
Why is it not constant? Why do you set an extra checkbox? I have never understood this, those who would enable it in the first place would also be the ones to check it in the second place.

**Comment by ihavenoface** [comment]
Because endless threads, endless discussion and never-ending butthurt over a small stupid (arguably stupid?) feature. Trust me when I say that this checkbox is the best compromise for both fronts on the matter.

**Comment by vampiricwulf** [comment]
`:I` That leaves me a little annoyed, I'd rather a second option that did it constantly, but you're the boss.

**Comment by vampiricwulf** [comment]
Especially since you removed PNG Thumbnail Fix and Auto-Gif, I'd assume it'd be natural to move to a constant Prefetch.

**Comment by ihavenoface** [comment]
It's not removed in the stable. I'm planning on smashing all three functions into one, see #80.

**Comment by vampiricwulf** [comment]
Ahh, I see, I understand now. Still would rather a second option for constant prefetch, but I understand.
