### ISSUE TITLE
Crosslinking to new threads return returns them as dead

### ISSUE THREAD

**Issue by Poilaucul** [ihavenoface/4chan-x#87]
Browsing /soc/ someone linked to a new thread and it appeared dead (linking to https://boards.4chan.org/soc/res/undefined) whereas it was in fact alive.

**Comment by ihavenoface** [comment]
This shouldn't be. Thank you for reporting.

**Comment by ihavenoface** [comment]
I found the issue with `undefined` but the deadlink isn't a 4chan x thing as far as I'm concerned.
