### ISSUE TITLE
Reply Links Incorrecly marked as (Cross-Thread)

### ISSUE THREAD

**Issue by Guillimet** [ihavenoface/4chan-x#95]
![reply_tags.png](https://f.cloud.github.com/assets/2146444/2913/07e5a63e-4280-11e2-9f86-1d31cc5ea8e2.png)
As you can see, 4chan X shows all reply links in a thread as cross-links, when they aren't.

When the thread is entered, or expanded from the board page, the problem vanishes.

The links themselves don't seem to load when they have "cross-thread" appended to them, outside of the threads.

**Comment by vampiricwulf** [comment]
Close #94, you made a duplicate issue.

**Comment by ihavenoface** [comment]
![wasd.png](https://f.cloud.github.com/assets/1175752/3299/3a54be22-42ba-11e2-8726-26ce20de80a3.png)

The last post in this image is indeed a link to a different thread so I'll just assume that this seemed to be a temporary thing.
Feel free to comment here if this still occurs though.

Also http://boards.4chan.org/q/res/322920#p322967
