### ISSUE TITLE
Feature Request: avoiding non-ASCII text filter on /r9k/

### ISSUE THREAD

**Issue by popman** [ihavenoface/4chan-x#97]
In order to use certain useful unicode characters that are blocked on /r9k/ replace certain characters with code before submitting the post, and have any post with the corresponding code be parsed back into the unicode equivalent.

e.g.
when someone types "I wouldn't ever believe someone earns an amount ≠ €300"
4chanX would submit "I wouldn't ever believe someone earns an amount [!=] [EUR]300"

and when a post is detected with "words, words, words [GBP]"
4chanX would replace it as "words, words, words £"

this would greatly improve the experience of /r9k/ users.
if you can suggest more useful unicode characters other than mathematical operators and currency symbols I would be happy to come up with codes to represent them.

**Comment by ihavenoface** [comment]
Generally I don't have anything against that but obviously I'm not into unicode yet.

**Comment by popman** [comment]
What do you mean by "not into unicode" you just need to make a bit of code to replace text before it gets posted.
The filter section of the code should have half of the work done for you.
