### ISSUE TITLE
Original Filename Download [Nightly]

### ISSUE THREAD

**Issue by vampiricwulf** [ihavenoface/4chan-x#98]
It has been added to nightly.
https://hg.mozilla.org/mozilla-central/rev/d6d585622ca7

`download="name.ext"`

Example html:
https://hg.mozilla.org/mozilla-central/file/d6d585622ca7/browser/base/content/test/download_page.html

**Comment by ihavenoface** [comment]
![scrot](https://f.cloud.github.com/assets/1175752/5436/661ac4b0-4379-11e2-8fc4-68f5194e1b87.png)
When I like one thing about mayhems code, it's its reliability.

**Comment by vampiricwulf** [comment]
Mayhem's opens up a new tab while nightly's download only works if it saves the file directly.

**Comment by ihavenoface** [comment]
`<a class="download_link entry" href="https://images.4chan.org/g/src/1355240340378.png" download="1354061124601.png">Download file</a>` seems right to me though.

**Comment by vampiricwulf** [comment]
Doesn't download it for me, it just opens up the image in the tab.

**Comment by ihavenoface** [comment]
Well I don't know what's wrong. The sample page at mozilla does the same for video files and slapping the actual path into the download attribute will just open the image in the current tab.

**Comment by ihavenoface** [comment]
Seems like I have to specify a mime type.

**Comment by vampiricwulf** [comment]
If you say so, I was just going to bring it up on the bug page since I want to know why it doesn't affect the "Save As...." name.

**Comment by ihavenoface** [comment]
> why it doesn't affect the "Save As...." name.

4chan x isn't even doing anything for that yet. I'm talking about the menu.

**Comment by vampiricwulf** [comment]
I know, I was saying that the dowbload attribute itself (on browser) should change the "Save As..." name.

**Comment by ihavenoface** [comment]
How would this work if the image doesn't have any download attribute?

**Comment by vampiricwulf** [comment]
"Save Link As..." on `Download Link`, but I was talking in general, like on the test HTML pages, I should be able to right-click and do "Save As..." and receive the same name recommendation as I would if I just clicked it rather than it keeping the original filename.

**Comment by ihavenoface** [comment]
Seems to be still a browser related issue. Closing for now.
