### ISSUE TITLE
Anonymise or not on a tripcode by tripcode basis

### ISSUE THREAD

**Issue by emoloney** [ihavenoface/4chan-x#99]
Could we get an /anonymise option and a /donotanonimise option in the tripcode filter settings? A lot of people I've talked to like the idea of anonymising, but don't do it because they have one or two tripcodes that they would always like to see. This would allow people to still see their favourite tripcodes without seeing the ones they don't want to, and without missing out on any of the conversation.

**Comment by ihavenoface** [comment]
#31
